import type { Skill, MathItem, Grade } from "./types"

// Avatar options
export const AVATARS = [
  { id: "unicorn", emoji: "🦄", name: "Unicorn" },
  { id: "robot", emoji: "🤖", name: "Robot" },
  { id: "cat", emoji: "😺", name: "Cat" },
  { id: "rocket", emoji: "🚀", name: "Rocket" },
  { id: "dragon", emoji: "🐉", name: "Dragon" },
  { id: "penguin", emoji: "🐧", name: "Penguin" },
]

// Grade 1 Skills
export const SKILLS: Skill[] = [
  // ========== GRADE 1: Georgia GSE Aligned ==========
  {
    id: "add-sub-within-10",
    name: "Addition & Subtraction within 10",
    category: "operations-algebraic",
    grade: 1,
    description: "Add and subtract numbers within 10",
    prerequisites: [],
  },
  {
    id: "add-sub-within-20",
    name: "Addition & Subtraction within 20",
    category: "operations-algebraic",
    grade: 1,
    description: "Add and subtract numbers within 20",
    prerequisites: ["add-sub-within-10"],
  },
  {
    id: "word-problems",
    name: "Word Problems",
    category: "operations-algebraic",
    grade: 1,
    description: "Solve addition and subtraction word problems",
    prerequisites: ["add-sub-within-10"],
  },
  {
    id: "number-sense-120",
    name: "Number Sense to 120",
    category: "number-place-value",
    grade: 1,
    description: "Understand place value and counting to 120",
    prerequisites: [],
  },
  {
    id: "compare-order",
    name: "Compare & Order Numbers",
    category: "number-place-value",
    grade: 1,
    description: "Compare and order numbers using <, >, =",
    prerequisites: ["number-sense-120"],
  },
  {
    id: "measurement-length",
    name: "Measurement & Length",
    category: "measurement",
    grade: 1,
    description: "Compare and measure lengths",
    prerequisites: [],
  },
  {
    id: "time-telling",
    name: "Telling Time",
    category: "time",
    grade: 1,
    description: "Tell time to the hour and half hour",
    prerequisites: [],
  },
  {
    id: "money-coins",
    name: "Money & Coins",
    category: "money",
    grade: 1,
    description: "Identify and count US coins",
    prerequisites: [],
  },
  {
    id: "geometry-shapes",
    name: "2D & 3D Shapes",
    category: "geometry",
    grade: 1,
    description: "Identify and describe shapes",
    prerequisites: [],
  },
  {
    id: "make-10",
    name: "Magic of 10",
    category: "operations-algebraic",
    grade: 1,
    description: "Find number pairs that add to 10",
    prerequisites: ["add-sub-within-10"],
  },
  {
    id: "doubles",
    name: "Doubles",
    category: "operations-algebraic",
    grade: 1,
    description: "Add a number to itself (doubles facts)",
    prerequisites: ["add-sub-within-10"],
  },
  {
    id: "add-9",
    name: "Adding 9",
    category: "operations-algebraic",
    grade: 1,
    description: "Add 9 using the add-10-subtract-1 strategy",
    prerequisites: ["make-10"],
  },
  {
    id: "halves",
    name: "Halves",
    category: "operations-algebraic",
    grade: 1,
    description: "Find half of even numbers",
    prerequisites: ["doubles"],
  },

  // Grade 2 Skills
  {
    id: "add-near-10",
    name: "Near 10 Addition",
    category: "addition",
    grade: 2,
    description: "Add numbers near 10 using compensation",
    prerequisites: ["add-9"],
  },
  {
    id: "multiply-by-10",
    name: "Multiply by 10",
    category: "multiplication",
    grade: 2,
    description: "Multiply any number by 10",
    prerequisites: [],
  },
  {
    id: "multiply-by-5",
    name: "Multiply by 5",
    category: "multiplication",
    grade: 2,
    description: "Multiply by 5 using halving and multiplying by 10",
    prerequisites: ["multiply-by-10", "halves"],
  },
  {
    id: "skip-count",
    name: "Skip Counting",
    category: "multiplication",
    grade: 2,
    description: "Count by 2s, 5s, and 10s",
    prerequisites: [],
  },
  // Grade 2 — standards-aligned core
  {
    id: "g2-add-100",
    name: "Add within 100",
    category: "addition",
    grade: 2,
    description: "Add two-digit numbers within 100 using place-value strategies",
    prerequisites: ["add-sub-within-20"],
  },
  {
    id: "g2-sub-100",
    name: "Subtract within 100",
    category: "subtraction",
    grade: 2,
    description: "Subtract two-digit numbers within 100, including regrouping",
    prerequisites: ["add-sub-within-20"],
  },
  {
    id: "g2-place-value-1000",
    name: "Place Value to 1000",
    category: "place-value",
    grade: 2,
    description: "Understand hundreds, tens, and ones; compare numbers to 1000",
    prerequisites: ["number-sense-120"],
  },
  {
    id: "g2-measurement",
    name: "Measurement & Length",
    category: "measurement",
    grade: 2,
    description: "Measure and compare lengths in standard units",
    prerequisites: ["measurement-length"],
  },
  {
    id: "g2-time",
    name: "Time to 5 Minutes",
    category: "time",
    grade: 2,
    description: "Tell and write time to the nearest five minutes",
    prerequisites: ["time-telling"],
  },
  {
    id: "g2-money",
    name: "Money & Making Change",
    category: "money",
    grade: 2,
    description: "Count coins and make change within a dollar",
    prerequisites: ["money-coins"],
  },
  // Grade 3 Skills
  {
    id: "multiply-by-11",
    name: "Multiply by 11",
    category: "multiplication",
    grade: 3,
    description: "Multiply 2-digit numbers by 11",
    prerequisites: ["multiply-by-10"],
  },
  {
    id: "divide-by-5",
    name: "Divide by 5",
    category: "division",
    grade: 3,
    description: "Divide by 5 using doubling and dividing by 10",
    prerequisites: ["multiply-by-5"],
  },
  {
    id: "square-ends-5",
    name: "Square Numbers Ending in 5",
    category: "multiplication",
    grade: 3,
    description: "Square any number ending in 5",
    prerequisites: ["multiply-by-10"],
  },
  {
    id: "same-tens-add-10",
    name: "Same Tens, Add to 10",
    category: "multiplication",
    grade: 3,
    description: "Multiply numbers with same tens digit and ones adding to 10",
    prerequisites: ["multiply-by-10"],
  },
  // Grade 4 Skills
  {
    id: "multiply-multi-digit",
    name: "Multiply Multi-Digit Numbers",
    category: "multiplication",
    grade: 4,
    description: "Multiply numbers up to 4 digits by 1-digit numbers",
    prerequisites: [],
  },
  {
    id: "divide-multi-digit",
    name: "Divide Multi-Digit Numbers",
    category: "division",
    grade: 4,
    description: "Divide numbers up to 4 digits by 1-digit divisors",
    prerequisites: [],
  },
  {
    id: "equivalent-fractions",
    name: "Equivalent Fractions",
    category: "fractions",
    grade: 4,
    description: "Recognize and generate equivalent fractions",
    prerequisites: [],
  },
  {
    id: "compare-fractions",
    name: "Compare Fractions",
    category: "fractions",
    grade: 4,
    description: "Compare two fractions with different numerators and denominators",
    prerequisites: ["equivalent-fractions"],
  },
  {
    id: "fractions-decimals",
    name: "Fractions & Decimals",
    category: "fractions",
    grade: 4,
    description: "Convert between fractions and decimals",
    prerequisites: ["equivalent-fractions"],
  },
  {
    id: "near-100-below",
    name: "Numbers Near 100 (Below)",
    category: "multiplication",
    grade: 4,
    description: "Multiply numbers just below 100",
    prerequisites: ["multiply-by-10"],
  },
  {
    id: "near-100-above",
    name: "Numbers Near 100 (Above)",
    category: "multiplication",
    grade: 4,
    description: "Multiply numbers just above 100",
    prerequisites: ["near-100-below"],
  },
  {
    id: "cross-multiply",
    name: "Cross Multiplication",
    category: "multiplication",
    grade: 4,
    description: "Multiply two 2-digit numbers using cross multiplication",
    prerequisites: ["multiply-by-11"],
  },
  {
    id: "divide-large-by-5",
    name: "Divide Large Numbers by 5",
    category: "division",
    grade: 4,
    description: "Divide any number by 5 quickly",
    prerequisites: ["divide-by-5"],
  },
  {
    id: "place-value",
    name: "Place Value to Millions",
    category: "place-value",
    grade: 4,
    description: "Understand large numbers and rounding",
    prerequisites: [],
  },
  {
    id: "measurement",
    name: "Measurement & Conversion",
    category: "measurement",
    grade: 4,
    description: "Convert units and solve measurement problems",
    prerequisites: [],
  },
  {
    id: "geometry",
    name: "Geometry & Angles",
    category: "geometry",
    grade: 4,
    description: "Classify shapes, measure angles",
    prerequisites: [],
  },

  // ========== GRADE 5: Common Core Aligned ==========
  {
    id: "g5-place-value",
    name: "Place Value & Powers of 10",
    category: "place-value",
    grade: 5,
    description: "Read, write, and round large numbers; multiply and divide by powers of 10",
    prerequisites: ["place-value"],
  },
  {
    id: "g5-mult",
    name: "Multi-Digit Multiplication",
    category: "multiplication",
    grade: 5,
    description: "Fluently multiply multi-digit whole numbers",
    prerequisites: ["multiply-multi-digit"],
  },
  {
    id: "g5-division",
    name: "Multi-Digit Division",
    category: "division",
    grade: 5,
    description: "Divide up to 4-digit dividends by 2-digit divisors",
    prerequisites: ["divide-multi-digit"],
  },
  {
    id: "g5-decimals",
    name: "Decimal Operations",
    category: "decimals",
    grade: 5,
    description: "Add, subtract, multiply, and round decimals to the hundredths",
    prerequisites: ["fractions-decimals"],
  },
  {
    id: "g5-add-sub-fractions",
    name: "Add & Subtract Fractions",
    category: "fractions",
    grade: 5,
    description: "Add and subtract fractions with unlike denominators",
    prerequisites: ["equivalent-fractions"],
  },
  {
    id: "g5-mult-fractions",
    name: "Multiply & Divide Fractions",
    category: "fractions",
    grade: 5,
    description: "Multiply fractions and divide with unit fractions",
    prerequisites: ["g5-add-sub-fractions"],
  },
  {
    id: "g5-expressions",
    name: "Expressions & Order of Operations",
    category: "operations-algebraic",
    grade: 5,
    description: "Evaluate numerical expressions using order of operations",
    prerequisites: [],
  },
  {
    id: "g5-measurement",
    name: "Measurement, Volume & Data",
    category: "measurement",
    grade: 5,
    description: "Convert units, find volume of rectangular prisms, and interpret data",
    prerequisites: ["measurement"],
  },
]

export const MATH_ITEMS: MathItem[] = [
  // ========== A. ADDITION & SUBTRACTION (within 10 & within 20) ==========
  // Core - Within 10
  {
    id: "add-sub-1",
    skillId: "add-sub-within-10",
    difficulty: 1,
    question: "3 + 5 = ?",
    answer: 8,
    choices: [6, 7, 8, 9],
    hint: "Count on from 3: 4, 5, 6, 7, 8",
    explanation: "3 + 5 = 8",
  },
  {
    id: "add-sub-2",
    skillId: "add-sub-within-10",
    difficulty: 1,
    question: "9 − 4 = ?",
    answer: 5,
    choices: [4, 5, 6, 7],
    hint: "Count back from 9: 8, 7, 6, 5",
    explanation: "9 − 4 = 5",
  },
  {
    id: "add-sub-3",
    skillId: "add-sub-within-10",
    difficulty: 1,
    question: "6 + 2 = ?",
    answer: 8,
    choices: [6, 7, 8, 9],
    hint: "Start at 6 and count up 2",
    explanation: "6 + 2 = 8",
  },
  {
    id: "add-sub-4",
    skillId: "add-sub-within-10",
    difficulty: 1,
    question: "10 − 7 = ?",
    answer: 3,
    choices: [2, 3, 4, 5],
    hint: "What do you need to add to 7 to get 10?",
    explanation: "10 − 7 = 3",
  },
  {
    id: "add-sub-5",
    skillId: "add-sub-within-10",
    difficulty: 1,
    question: "8 + 1 = ?",
    answer: 9,
    choices: [7, 8, 9, 10],
    hint: "Adding 1 means the next number",
    explanation: "8 + 1 = 9",
  },

  // Core - Within 20
  {
    id: "add-sub-6",
    skillId: "add-sub-within-20",
    difficulty: 2,
    question: "14 − 6 = ?",
    answer: 8,
    choices: [6, 7, 8, 9],
    hint: "Think: 14 = 10 + 4, subtract 6",
    explanation: "14 − 6 = 8",
  },
  {
    id: "add-sub-7",
    skillId: "add-sub-within-20",
    difficulty: 2,
    question: "7 + 7 = ?",
    answer: 14,
    choices: [12, 13, 14, 15],
    hint: "Doubles are special! 7 + 7",
    explanation: "7 + 7 = 14. This is called a double!",
    vedicTrick: {
      name: "Doubles Strategy",
      steps: [
        "When you add a number to itself, it's called a double",
        "7 + 7 = 14",
        "Memorize your doubles - they're super useful!",
      ],
    },
  },
  {
    id: "add-sub-8",
    skillId: "add-sub-within-20",
    difficulty: 2,
    question: "15 − 9 = ?",
    answer: 6,
    choices: [4, 5, 6, 7],
    hint: "Count up from 9 to 15",
    explanation: "15 − 9 = 6",
  },

  // Word Problems
  {
    id: "word-1",
    skillId: "word-problems",
    difficulty: 2,
    question: "Ana has 5 apples. She gets 3 more. How many apples does she have?",
    answer: 8,
    choices: [6, 7, 8, 9],
    hint: "You're adding apples together",
    explanation: "5 + 3 = 8 apples",
  },
  {
    id: "word-2",
    skillId: "word-problems",
    difficulty: 2,
    question: "You see 12 birds. 4 fly away. How many are left?",
    answer: 8,
    choices: [6, 7, 8, 9],
    hint: "When birds fly away, we subtract",
    explanation: "12 − 4 = 8 birds",
  },
  {
    id: "word-3",
    skillId: "word-problems",
    difficulty: 2,
    question: "Tom has 7 cookies. He eats 2. How many remain?",
    answer: 5,
    choices: [4, 5, 6, 7],
    hint: "Eating means taking away",
    explanation: "7 − 2 = 5 cookies",
  },

  // Challenge
  {
    id: "challenge-1",
    skillId: "add-sub-within-20",
    difficulty: 4,
    question: "I think of a number. When I add 8, I get 15. What is my number?",
    answer: 7,
    choices: [5, 6, 7, 8],
    hint: "What plus 8 equals 15?",
    explanation: "? + 8 = 15, so ? = 7",
  },

  // ========== B. NUMBER SENSE & PLACE VALUE (Up to 120) ==========
  {
    id: "place-1",
    skillId: "number-sense-120",
    difficulty: 2,
    question: "What number is 4 tens and 2 ones?",
    answer: 42,
    choices: [24, 42, 44, 52],
    hint: "4 tens means 40, add 2 ones",
    explanation: "4 tens = 40, plus 2 ones = 42",
    vedicTrick: {
      name: "Place Value Strategy",
      steps: ["Tens place tells you groups of 10", "4 tens = 40", "Add the ones: 40 + 2 = 42"],
    },
  },
  {
    id: "place-2",
    skillId: "number-sense-120",
    difficulty: 2,
    question: "What number is 10 more than 37?",
    answer: 47,
    choices: [38, 45, 47, 48],
    hint: "Adding 10 changes the tens place",
    explanation: "37 + 10 = 47",
  },
  {
    id: "place-3",
    skillId: "number-sense-120",
    difficulty: 2,
    question: "What number is 10 less than 64?",
    answer: 54,
    choices: [53, 54, 63, 74],
    hint: "Subtracting 10 changes the tens place",
    explanation: "64 − 10 = 54",
  },
  {
    id: "place-4",
    skillId: "number-sense-120",
    difficulty: 2,
    question: "Which is greater: 58 or 49?",
    answer: 58,
    choices: [49, 58],
    hint: "Look at the tens place first",
    explanation: "58 is greater because 5 tens > 4 tens",
  },
  {
    id: "place-5",
    skillId: "number-sense-120",
    difficulty: 1,
    question: "What number comes after 79?",
    answer: 80,
    choices: [78, 79, 80, 81],
    hint: "Count up by 1",
    explanation: "After 79 comes 80",
  },
  {
    id: "place-6",
    skillId: "number-sense-120",
    difficulty: 1,
    question: "What number comes before 100?",
    answer: 99,
    choices: [98, 99, 100, 101],
    hint: "Count back by 1",
    explanation: "Before 100 comes 99",
  },
  {
    id: "place-7",
    skillId: "number-sense-120",
    difficulty: 3,
    question: "Which number has 6 tens?",
    answer: 63,
    choices: [46, 60, 63, 66],
    hint: "6 tens means 60 in the tens place",
    explanation: "63 has 6 tens and 3 ones",
  },
  {
    id: "place-8",
    skillId: "number-sense-120",
    difficulty: 3,
    question: "Which number has more ones: 52 or 59?",
    answer: 59,
    choices: [52, 59],
    hint: "Look at the ones place",
    explanation: "59 has 9 ones, 52 has 2 ones. 9 > 2",
  },
  {
    id: "place-9",
    skillId: "number-sense-120",
    difficulty: 2,
    question: "Count by tens starting at 30. What comes after 50?",
    answer: 60,
    choices: [40, 51, 60, 70],
    hint: "30, 40, 50, ?",
    explanation: "30, 40, 50, 60 (add 10 each time)",
  },
  {
    id: "place-10",
    skillId: "number-sense-120",
    difficulty: 4,
    question: "Which number is larger: 3 tens + 9 ones OR 45?",
    answer: 45,
    choices: [39, 45],
    hint: "First figure out what 3 tens + 9 ones equals",
    explanation: "3 tens + 9 ones = 39. 45 > 39",
  },

  // ========== C. COMPARING NUMBERS & ORDERING ==========
  {
    id: "compare-1",
    skillId: "compare-order",
    difficulty: 2,
    question: "9 ___ 6. Which symbol? (<, >, =)",
    answer: ">",
    choices: ["<", ">", "="],
    hint: "9 is bigger than 6",
    explanation: "9 > 6 (9 is greater than 6)",
  },
  {
    id: "compare-2",
    skillId: "compare-order",
    difficulty: 2,
    question: "15 ___ 12. Which symbol?",
    answer: ">",
    choices: ["<", ">", "="],
    hint: "Which number is larger?",
    explanation: "15 > 12",
  },
  {
    id: "compare-3",
    skillId: "compare-order",
    difficulty: 2,
    question: "27 ___ 30. Which symbol?",
    answer: "<",
    choices: ["<", ">", "="],
    hint: "Is 27 less than or greater than 30?",
    explanation: "27 < 30 (27 is less than 30)",
  },
  {
    id: "compare-4",
    skillId: "compare-order",
    difficulty: 3,
    question: "Which number is closest to 20: 18 or 25?",
    answer: 18,
    choices: [18, 25],
    hint: "How far is each number from 20?",
    explanation: "18 is 2 away, 25 is 5 away. 18 is closer!",
  },

  // ========== D. MEASUREMENT (Length, Weight, Capacity) ==========
  {
    id: "measure-1",
    skillId: "measurement-length",
    difficulty: 1,
    question: "Which is longer: a crayon or a marker?",
    answer: "marker",
    choices: ["crayon", "marker"],
    hint: "Think about what you use in class",
    explanation: "Most markers are longer than crayons",
  },
  {
    id: "measure-2",
    skillId: "measurement-length",
    difficulty: 1,
    question: "Which weighs more: a feather or a book?",
    answer: "book",
    choices: ["feather", "book"],
    hint: "Which one is harder to lift?",
    explanation: "A book weighs much more than a feather",
  },
  {
    id: "measure-3",
    skillId: "measurement-length",
    difficulty: 1,
    question: "Which holds more water: a cup or a bucket?",
    answer: "bucket",
    choices: ["cup", "bucket"],
    hint: "Think about size",
    explanation: "A bucket holds much more water than a cup",
  },
  {
    id: "measure-4",
    skillId: "measurement-length",
    difficulty: 2,
    question: "Line A is 6 cubes long. Line B is 4 cubes long. Which is longer?",
    answer: "Line A",
    choices: ["Line A", "Line B"],
    hint: "Compare the numbers",
    explanation: "6 cubes > 4 cubes, so Line A is longer",
  },

  // ========== E. TIME (to the Hour & Half Hour) ==========
  {
    id: "time-1",
    skillId: "time-telling",
    difficulty: 2,
    question: "When the short hand is on 3 and long hand is on 12, what time is it?",
    answer: "3:00",
    choices: ["2:00", "3:00", "12:00", "3:30"],
    hint: "Short hand shows the hour",
    explanation: "When the long hand is on 12, we read the hour. 3:00",
  },
  {
    id: "time-2",
    skillId: "time-telling",
    difficulty: 3,
    question: "When the short hand is between 7 and 8, and long hand is on 6, what time is it?",
    answer: "7:30",
    choices: ["6:30", "7:00", "7:30", "8:00"],
    hint: "Long hand on 6 means 30 minutes (half hour)",
    explanation: "7:30 (half past 7)",
  },
  {
    id: "time-3",
    skillId: "time-telling",
    difficulty: 2,
    question: "What time is 1 hour after 4:00?",
    answer: "5:00",
    choices: ["3:00", "4:00", "5:00", "6:00"],
    hint: "Add 1 to the hour",
    explanation: "4:00 + 1 hour = 5:00",
  },
  {
    id: "time-4",
    skillId: "time-telling",
    difficulty: 2,
    question: "What time is 1 hour before 9:00?",
    answer: "8:00",
    choices: ["7:00", "8:00", "9:00", "10:00"],
    hint: "Subtract 1 from the hour",
    explanation: "9:00 − 1 hour = 8:00",
  },
  {
    id: "time-5",
    skillId: "time-telling",
    difficulty: 4,
    question: "What time is halfway between 2:00 and 3:00?",
    answer: "2:30",
    choices: ["2:00", "2:30", "3:00", "3:30"],
    hint: "Halfway is 30 minutes",
    explanation: "Halfway between 2:00 and 3:00 is 2:30",
  },

  // ========== F. MONEY (US Coins) ==========
  {
    id: "money-1",
    skillId: "money-coins",
    difficulty: 1,
    question: "How much is a penny worth?",
    answer: "1¢",
    choices: ["1¢", "5¢", "10¢", "25¢"],
    hint: "A penny is the smallest coin",
    explanation: "A penny = 1 cent",
  },
  {
    id: "money-2",
    skillId: "money-coins",
    difficulty: 1,
    question: "How much is a nickel worth?",
    answer: "5¢",
    choices: ["1¢", "5¢", "10¢", "25¢"],
    hint: "A nickel is bigger than a penny",
    explanation: "A nickel = 5 cents",
  },
  {
    id: "money-3",
    skillId: "money-coins",
    difficulty: 1,
    question: "How much is a dime worth?",
    answer: "10¢",
    choices: ["1¢", "5¢", "10¢", "25¢"],
    hint: "A dime is small but worth a lot",
    explanation: "A dime = 10 cents",
  },
  {
    id: "money-4",
    skillId: "money-coins",
    difficulty: 1,
    question: "How much is a quarter worth?",
    answer: "25¢",
    choices: ["1¢", "5¢", "10¢", "25¢"],
    hint: "A quarter is the biggest coin shown",
    explanation: "A quarter = 25 cents",
  },
  {
    id: "money-5",
    skillId: "money-coins",
    difficulty: 2,
    question: "You have 2 dimes. How much money is that?",
    answer: "20¢",
    choices: ["10¢", "15¢", "20¢", "25¢"],
    hint: "Each dime is 10¢",
    explanation: "2 dimes = 10¢ + 10¢ = 20¢",
    vedicTrick: {
      name: "Skip Counting by 10s",
      steps: ["Each dime = 10¢", "Count by 10s: 10, 20", "2 dimes = 20¢"],
    },
  },
  {
    id: "money-6",
    skillId: "money-coins",
    difficulty: 3,
    question: "You have 1 quarter and 1 nickel. How much total?",
    answer: "30¢",
    choices: ["25¢", "30¢", "35¢", "40¢"],
    hint: "Add 25¢ + 5¢",
    explanation: "25¢ + 5¢ = 30¢",
  },

  // ========== G. GEOMETRY (2D & 3D Shapes) ==========
  {
    id: "geo-1",
    skillId: "geometry-shapes",
    difficulty: 1,
    question: "How many sides does a triangle have?",
    answer: 3,
    choices: [2, 3, 4, 5],
    hint: "Tri means three",
    explanation: "A triangle has 3 sides",
  },
  {
    id: "geo-2",
    skillId: "geometry-shapes",
    difficulty: 1,
    question: "Which shape has 4 equal sides?",
    answer: "square",
    choices: ["triangle", "square", "circle", "rectangle"],
    hint: "Think about same length sides",
    explanation: "A square has 4 equal sides",
  },
  {
    id: "geo-3",
    skillId: "geometry-shapes",
    difficulty: 2,
    question: "Which shape can roll?",
    answer: "sphere",
    choices: ["cube", "sphere", "square", "triangle"],
    hint: "What shape is a ball?",
    explanation: "A sphere (like a ball) can roll",
  },
  {
    id: "geo-4",
    skillId: "geometry-shapes",
    difficulty: 2,
    question: "Which shape has a curved surface?",
    answer: "sphere",
    choices: ["cube", "sphere"],
    hint: "Think about a ball",
    explanation: "A sphere has a curved surface; a cube has flat faces",
  },
  {
    id: "geo-5",
    skillId: "geometry-shapes",
    difficulty: 3,
    question: "How many sides does a pentagon have?",
    answer: 5,
    choices: [4, 5, 6, 7],
    hint: "Penta means five",
    explanation: "A pentagon has 5 sides",
  },

  // ========== GRADE 1: Magic of 10 ==========
  {
    id: "make10-1",
    skillId: "make-10",
    difficulty: 1,
    question: "1 + ? = 10",
    answer: 9,
    choices: [7, 8, 9, 10],
    hint: "What number pairs with 1 to make 10?",
    explanation: "1 and 9 are best friends - they make 10!",
    vedicTrick: {
      name: "Magic of 10",
      steps: ["Numbers that add to 10 are your best friends!", "1 + 9 = 10", "Remember: 1 and 9 are a magic pair!"],
    },
  },
  {
    id: "make10-2",
    skillId: "make-10",
    difficulty: 1,
    question: "2 + ? = 10",
    answer: 8,
    choices: [6, 7, 8, 9],
    hint: "2 needs a friend to make 10",
    explanation: "2 and 8 are best friends - they make 10!",
    vedicTrick: {
      name: "Magic of 10",
      steps: ["Find the number that makes 10 with 2", "2 + 8 = 10", "2 and 8 are a magic pair!"],
    },
  },
  {
    id: "make10-3",
    skillId: "make-10",
    difficulty: 1,
    question: "3 + ? = 10",
    answer: 7,
    choices: [5, 6, 7, 8],
    hint: "3 and which number make 10?",
    explanation: "3 and 7 are best friends - they make 10!",
    vedicTrick: {
      name: "Magic of 10",
      steps: ["3 + 7 = 10", "3 and 7 are a magic pair!", "Look for 10-pairs when adding!"],
    },
  },
  {
    id: "make10-4",
    skillId: "make-10",
    difficulty: 1,
    question: "4 + ? = 10",
    answer: 6,
    choices: [4, 5, 6, 7],
    hint: "4 plus what equals 10?",
    explanation: "4 and 6 are best friends - they make 10!",
    vedicTrick: {
      name: "Magic of 10",
      steps: ["4 + 6 = 10", "4 and 6 are a magic pair!", "These pairs help you add faster!"],
    },
  },
  {
    id: "make10-5",
    skillId: "make-10",
    difficulty: 1,
    question: "5 + ? = 10",
    answer: 5,
    choices: [4, 5, 6, 7],
    hint: "5 is special - it pairs with itself!",
    explanation: "5 + 5 = 10! Five is its own best friend!",
    vedicTrick: {
      name: "Magic of 10",
      steps: ["5 + 5 = 10", "5 is special - it's its own magic pair!", "Double 5 always equals 10!"],
    },
  },
  {
    id: "make10-6",
    skillId: "make-10",
    difficulty: 1,
    question: "6 + ? = 10",
    answer: 4,
    choices: [3, 4, 5, 6],
    hint: "6 and which number are best friends?",
    explanation: "6 and 4 are best friends - they make 10!",
    vedicTrick: {
      name: "Magic of 10",
      steps: ["6 + 4 = 10", "This is the same as 4 + 6!", "Order doesn't matter in addition!"],
    },
  },
  {
    id: "make10-7",
    skillId: "make-10",
    difficulty: 1,
    question: "7 + ? = 10",
    answer: 3,
    choices: [2, 3, 4, 5],
    hint: "7 needs a friend to make 10",
    explanation: "7 and 3 are best friends - they make 10!",
    vedicTrick: {
      name: "Magic of 10",
      steps: ["7 + 3 = 10", "Same as 3 + 7!", "Magic pairs work both ways!"],
    },
  },
  {
    id: "make10-8",
    skillId: "make-10",
    difficulty: 1,
    question: "8 + ? = 10",
    answer: 2,
    choices: [1, 2, 3, 4],
    hint: "What pairs with 8 to make 10?",
    explanation: "8 and 2 are best friends - they make 10!",
    vedicTrick: {
      name: "Magic of 10",
      steps: ["8 + 2 = 10", "8 and 2 are magic partners!", "Remember these pairs!"],
    },
  },
  {
    id: "make10-9",
    skillId: "make-10",
    difficulty: 1,
    question: "9 + ? = 10",
    answer: 1,
    choices: [0, 1, 2, 3],
    hint: "9 is almost 10!",
    explanation: "9 and 1 are best friends - they make 10!",
    vedicTrick: {
      name: "Magic of 10",
      steps: ["9 + 1 = 10", "9 needs just 1 more!", "The smallest magic pair!"],
    },
  },
  {
    id: "make10-10",
    skillId: "make-10",
    difficulty: 2,
    question: "3 + 4 + ? = 10",
    answer: 3,
    choices: [2, 3, 4, 5],
    hint: "First add 3 + 4, then find what makes 10",
    explanation: "3 + 4 = 7, and 7 + 3 = 10!",
    vedicTrick: {
      name: "Magic of 10",
      steps: [
        "Add the first two: 3 + 4 = 7",
        "Now use your magic pairs: 7 + 3 = 10",
        "Break big problems into smaller ones!",
      ],
    },
  },
  {
    id: "make10-11",
    skillId: "make-10",
    difficulty: 2,
    question: "2 + 5 + ? = 10",
    answer: 3,
    choices: [2, 3, 4, 5],
    hint: "Add 2 + 5 first",
    explanation: "2 + 5 = 7, and 7 + 3 = 10!",
    vedicTrick: {
      name: "Magic of 10",
      steps: ["2 + 5 = 7", "7 + 3 = 10", "Use what you know!"],
    },
  },
  {
    id: "make10-12",
    skillId: "make-10",
    difficulty: 2,
    question: "1 + 6 + ? = 10",
    answer: 3,
    choices: [2, 3, 4, 5],
    hint: "1 + 6 = 7",
    explanation: "1 + 6 = 7, and 7 + 3 = 10!",
    vedicTrick: {
      name: "Magic of 10",
      steps: ["1 + 6 = 7", "7 and 3 are magic friends!", "Answer: 3"],
    },
  },

  // ========== GRADE 1: Doubles ==========
  {
    id: "double-1",
    skillId: "doubles",
    difficulty: 1,
    question: "2 + 2 = ?",
    answer: 4,
    choices: [3, 4, 5, 6],
    hint: "Double means the same number twice!",
    explanation: "When you double 2, you get 4!",
    vedicTrick: {
      name: "Double Trouble",
      steps: ["Doubling means adding a number to itself", "2 + 2 = 4", "You're counting 2 two times!"],
    },
  },
  {
    id: "double-2",
    skillId: "doubles",
    difficulty: 1,
    question: "3 + 3 = ?",
    answer: 6,
    choices: [5, 6, 7, 8],
    hint: "What is double 3?",
    explanation: "Double 3 is 6!",
    vedicTrick: {
      name: "Double Trouble",
      steps: ["3 + 3 = 6", "Doubles grow fast like magic!", "If you know your doubles, math gets easy!"],
    },
  },
  {
    id: "double-3",
    skillId: "doubles",
    difficulty: 1,
    question: "4 + 4 = ?",
    answer: 8,
    choices: [6, 7, 8, 9],
    hint: "What is double 4?",
    explanation: "Double 4 is 8!",
    vedicTrick: {
      name: "Double Trouble",
      steps: ["4 + 4 = 8", "Four fingers on each hand = 8 fingers!", "Doubles are super useful!"],
    },
  },
  {
    id: "double-4",
    skillId: "doubles",
    difficulty: 2,
    question: "5 + 5 = ?",
    answer: 10,
    choices: [8, 9, 10, 11],
    hint: "What is double 5?",
    explanation: "Double 5 is 10! This is also a Magic 10!",
    vedicTrick: {
      name: "Double Trouble",
      steps: ["5 + 5 = 10", "Double 5 equals 10!", "This is also a Magic of 10 trick!"],
    },
  },
  {
    id: "double-5",
    skillId: "doubles",
    difficulty: 2,
    question: "6 + 6 = ?",
    answer: 12,
    choices: [10, 11, 12, 13],
    hint: "What is double 6?",
    explanation: "Double 6 is 12!",
    vedicTrick: {
      name: "Double Trouble",
      steps: ["6 + 6 = 12", "Six doubled jumps past 10!", "Doubles help you multiply by 2!"],
    },
  },
  {
    id: "double-6",
    skillId: "doubles",
    difficulty: 1,
    question: "1 + 1 = ?",
    answer: 2,
    choices: [1, 2, 3, 4],
    hint: "What is double 1?",
    explanation: "Double 1 is 2!",
    vedicTrick: {
      name: "Double Trouble",
      steps: ["1 + 1 = 2", "The simplest double!", "Even 1 can be doubled!"],
    },
  },
  {
    id: "double-7",
    skillId: "doubles",
    difficulty: 2,
    question: "7 + 7 = ?",
    answer: 14,
    choices: [12, 13, 14, 15],
    hint: "What is double 7?",
    explanation: "Double 7 is 14!",
    vedicTrick: {
      name: "Double Trouble",
      steps: ["7 + 7 = 14", "Lucky 7 doubled!", "14 is 2 weeks of days!"],
    },
  },
  {
    id: "double-8",
    skillId: "doubles",
    difficulty: 2,
    question: "8 + 8 = ?",
    answer: 16,
    choices: [14, 15, 16, 17],
    hint: "What is double 8?",
    explanation: "Double 8 is 16!",
    vedicTrick: {
      name: "Double Trouble",
      steps: ["8 + 8 = 16", "Sixteen is sweet sixteen!", "Great for learning to multiply!"],
    },
  },
  {
    id: "double-9",
    skillId: "doubles",
    difficulty: 2,
    question: "9 + 9 = ?",
    answer: 18,
    choices: [16, 17, 18, 19],
    hint: "What is double 9?",
    explanation: "Double 9 is 18!",
    vedicTrick: {
      name: "Double Trouble",
      steps: ["9 + 9 = 18", "Almost 20!", "Doubles are the base of multiplication!"],
    },
  },
  {
    id: "double-10",
    skillId: "doubles",
    difficulty: 2,
    question: "10 + 10 = ?",
    answer: 20,
    choices: [18, 19, 20, 21],
    hint: "What is double 10?",
    explanation: "Double 10 is 20!",
    vedicTrick: {
      name: "Double Trouble",
      steps: ["10 + 10 = 20", "Ten plus ten equals twenty!", "Now you're in the twenties!"],
    },
  },
  {
    id: "double-11",
    skillId: "doubles",
    difficulty: 1,
    question: "If you have 3 pairs of socks, how many socks do you have?",
    answer: 6,
    choices: [4, 5, 6, 7],
    hint: "Each pair has 2 socks!",
    explanation: "3 pairs × 2 socks = 6 socks. This is 3 + 3!",
    vedicTrick: {
      name: "Double Trouble",
      steps: ["3 pairs = 3 + 3", "3 + 3 = 6", "Doubles are everywhere in real life!"],
    },
  },
  {
    id: "double-12",
    skillId: "doubles",
    difficulty: 2,
    question: "If you have 4 pairs of shoes, how many shoes do you have?",
    answer: 8,
    choices: [6, 7, 8, 9],
    hint: "Each pair has 2 shoes!",
    explanation: "4 pairs × 2 shoes = 8 shoes. This is 4 + 4!",
    vedicTrick: {
      name: "Double Trouble",
      steps: ["4 pairs = 4 + 4", "4 + 4 = 8", "Pairs are doubles!"],
    },
  },

  // ========== GRADE 1: Adding 9 ==========
  {
    id: "add9-1",
    skillId: "add-9",
    difficulty: 2,
    question: "5 + 9 = ?",
    answer: 14,
    choices: [13, 14, 15, 16],
    hint: "Add 10 first, then subtract 1",
    explanation: "5 + 9 = 5 + 10 - 1 = 15 - 1 = 14",
    vedicTrick: {
      name: "Magic of 9",
      steps: ["Adding 9 is easy: add 10, then subtract 1!", "5 + 10 = 15", "15 - 1 = 14"],
    },
  },
  {
    id: "add9-2",
    skillId: "add-9",
    difficulty: 2,
    question: "7 + 9 = ?",
    answer: 16,
    choices: [14, 15, 16, 17],
    hint: "Add 10 first, then subtract 1",
    explanation: "7 + 9 = 7 + 10 - 1 = 17 - 1 = 16",
    vedicTrick: {
      name: "Magic of 9",
      steps: ["Add 10 to 7: 7 + 10 = 17", "Subtract 1: 17 - 1 = 16", "Adding 9 = Adding 10 minus 1!"],
    },
  },
  {
    id: "add9-3",
    skillId: "add-9",
    difficulty: 2,
    question: "8 + 9 = ?",
    answer: 17,
    choices: [15, 16, 17, 18],
    hint: "Add 10 first, then take away 1",
    explanation: "8 + 9 = 8 + 10 - 1 = 18 - 1 = 17",
    vedicTrick: {
      name: "Magic of 9",
      steps: ["8 + 10 = 18", "18 - 1 = 17", "9 is just 10 minus 1!"],
    },
  },
  {
    id: "add9-4",
    skillId: "add-9",
    difficulty: 2,
    question: "6 + 9 = ?",
    answer: 15,
    choices: [13, 14, 15, 16],
    hint: "Think: 6 + 10 - 1",
    explanation: "6 + 9 = 6 + 10 - 1 = 16 - 1 = 15",
    vedicTrick: {
      name: "Magic of 9",
      steps: ["6 + 10 = 16", "16 - 1 = 15", "This trick works with any number!"],
    },
  },
  {
    id: "add9-5",
    skillId: "add-9",
    difficulty: 2,
    question: "3 + 9 = ?",
    answer: 12,
    choices: [11, 12, 13, 14],
    hint: "Add 10, subtract 1",
    explanation: "3 + 9 = 3 + 10 - 1 = 13 - 1 = 12",
    vedicTrick: {
      name: "Magic of 9",
      steps: ["3 + 10 = 13", "13 - 1 = 12", "9 is always 10 - 1!"],
    },
  },
  {
    id: "add9-6",
    skillId: "add-9",
    difficulty: 2,
    question: "4 + 9 = ?",
    answer: 13,
    choices: [12, 13, 14, 15],
    hint: "Think of 10, then take away 1",
    explanation: "4 + 9 = 4 + 10 - 1 = 14 - 1 = 13",
    vedicTrick: {
      name: "Magic of 9",
      steps: ["4 + 10 = 14", "14 - 1 = 13", "Super quick!"],
    },
  },
  {
    id: "add9-7",
    skillId: "add-9",
    difficulty: 2,
    question: "2 + 9 = ?",
    answer: 11,
    choices: [10, 11, 12, 13],
    hint: "Add 10 first, then subtract 1",
    explanation: "2 + 9 = 2 + 10 - 1 = 12 - 1 = 11",
    vedicTrick: {
      name: "Magic of 9",
      steps: ["2 + 10 = 12", "12 - 1 = 11", "Easy peasy!"],
    },
  },
  {
    id: "add9-8",
    skillId: "add-9",
    difficulty: 2,
    question: "1 + 9 = ?",
    answer: 10,
    choices: [9, 10, 11, 12],
    hint: "1 + 10 - 1 = ?",
    explanation: "1 + 9 = 10! This is a magic pair!",
    vedicTrick: {
      name: "Magic of 9",
      steps: ["1 + 10 = 11", "11 - 1 = 10", "Also a magic 10 pair!"],
    },
  },
  {
    id: "add9-9",
    skillId: "add-9",
    difficulty: 3,
    question: "9 + 9 = ?",
    answer: 18,
    choices: [16, 17, 18, 19],
    hint: "This is also a double!",
    explanation: "9 + 9 = 18! You can use doubles or the 9 trick!",
    vedicTrick: {
      name: "Magic of 9",
      steps: ["Two ways: 9 + 10 - 1 = 18", "Or: 9 + 9 = 18 (double)", "Both work!"],
    },
  },
  {
    id: "add9-10",
    skillId: "add-9",
    difficulty: 3,
    question: "10 + 9 = ?",
    answer: 19,
    choices: [17, 18, 19, 20],
    hint: "10 is easy to add!",
    explanation: "10 + 9 = 19",
    vedicTrick: {
      name: "Magic of 9",
      steps: ["10 + 10 = 20", "20 - 1 = 19", "Or just add 9 to 10 directly!"],
    },
  },
  {
    id: "add9-11",
    skillId: "add-9",
    difficulty: 3,
    question: "11 + 9 = ?",
    answer: 20,
    choices: [18, 19, 20, 21],
    hint: "11 + 10 - 1",
    explanation: "11 + 9 = 11 + 10 - 1 = 21 - 1 = 20",
    vedicTrick: {
      name: "Magic of 9",
      steps: ["11 + 10 = 21", "21 - 1 = 20", "Works with any number!"],
    },
  },

  // ========== GRADE 1: Halves ==========
  {
    id: "half-1",
    skillId: "halves",
    difficulty: 1,
    question: "Half of 10 = ?",
    answer: 5,
    choices: [4, 5, 6, 7],
    hint: "What number doubled makes 10?",
    explanation: "Half of 10 is 5, because 5 + 5 = 10!",
    vedicTrick: {
      name: "Half and Double",
      steps: [
        "Halving is the opposite of doubling!",
        "5 + 5 = 10, so half of 10 = 5",
        "If you know doubles, you know halves!",
      ],
    },
  },
  {
    id: "half-2",
    skillId: "halves",
    difficulty: 1,
    question: "Half of 6 = ?",
    answer: 3,
    choices: [2, 3, 4, 5],
    hint: "3 + 3 = 6",
    explanation: "Half of 6 is 3!",
    vedicTrick: {
      name: "Half and Double",
      steps: ["3 + 3 = 6", "So half of 6 = 3", "Doubles help you find halves!"],
    },
  },
  {
    id: "half-3",
    skillId: "halves",
    difficulty: 1,
    question: "Half of 8 = ?",
    answer: 4,
    choices: [3, 4, 5, 6],
    hint: "4 + 4 = 8",
    explanation: "Half of 8 is 4!",
    vedicTrick: {
      name: "Half and Double",
      steps: ["4 + 4 = 8", "So half of 8 = 4", "Think of your doubles backwards!"],
    },
  },
  {
    id: "half-4",
    skillId: "halves",
    difficulty: 1,
    question: "Half of 4 = ?",
    answer: 2,
    choices: [1, 2, 3, 4],
    hint: "2 + 2 = 4",
    explanation: "Half of 4 is 2!",
    vedicTrick: {
      name: "Half and Double",
      steps: ["2 + 2 = 4", "So half of 4 = 2", "Split it in the middle!"],
    },
  },
  {
    id: "half-5",
    skillId: "halves",
    difficulty: 1,
    question: "Half of 2 = ?",
    answer: 1,
    choices: [0, 1, 2, 3],
    hint: "1 + 1 = 2",
    explanation: "Half of 2 is 1!",
    vedicTrick: {
      name: "Half and Double",
      steps: ["1 + 1 = 2", "So half of 2 = 1", "The smallest half!"],
    },
  },
  {
    id: "half-6",
    skillId: "halves",
    difficulty: 2,
    question: "Half of 12 = ?",
    answer: 6,
    choices: [5, 6, 7, 8],
    hint: "6 + 6 = 12",
    explanation: "Half of 12 is 6!",
    vedicTrick: {
      name: "Half and Double",
      steps: ["6 + 6 = 12", "So half of 12 = 6", "Like splitting a dozen eggs!"],
    },
  },
  {
    id: "half-7",
    skillId: "halves",
    difficulty: 2,
    question: "Half of 14 = ?",
    answer: 7,
    choices: [6, 7, 8, 9],
    hint: "7 + 7 = 14",
    explanation: "Half of 14 is 7!",
    vedicTrick: {
      name: "Half and Double",
      steps: ["7 + 7 = 14", "So half of 14 = 7", "Lucky seven!"],
    },
  },
  {
    id: "half-8",
    skillId: "halves",
    difficulty: 2,
    question: "Half of 16 = ?",
    answer: 8,
    choices: [7, 8, 9, 10],
    hint: "8 + 8 = 16",
    explanation: "Half of 16 is 8!",
    vedicTrick: {
      name: "Half and Double",
      steps: ["8 + 8 = 16", "So half of 16 = 8", "Perfect split!"],
    },
  },
  {
    id: "half-9",
    skillId: "halves",
    difficulty: 2,
    question: "Half of 18 = ?",
    answer: 9,
    choices: [8, 9, 10, 11],
    hint: "9 + 9 = 18",
    explanation: "Half of 18 is 9!",
    vedicTrick: {
      name: "Half and Double",
      steps: ["9 + 9 = 18", "So half of 18 = 9", "Almost 10!"],
    },
  },
  {
    id: "half-10",
    skillId: "halves",
    difficulty: 2,
    question: "Half of 20 = ?",
    answer: 10,
    choices: [9, 10, 11, 12],
    hint: "10 + 10 = 20",
    explanation: "Half of 20 is 10!",
    vedicTrick: {
      name: "Half and Double",
      steps: ["10 + 10 = 20", "So half of 20 = 10", "Two tens make twenty!"],
    },
  },
  {
    id: "half-11",
    skillId: "halves",
    difficulty: 1,
    question: "If you have 8 cookies and share equally with your friend, how many do you each get?",
    answer: 4,
    choices: [3, 4, 5, 6],
    hint: "Split 8 in half",
    explanation: "8 ÷ 2 = 4. You each get 4 cookies!",
    vedicTrick: {
      name: "Half and Double",
      steps: ["Sharing equally means finding half", "Half of 8 = 4", "4 + 4 = 8"],
    },
  },
  {
    id: "half-12",
    skillId: "halves",
    difficulty: 2,
    question: "If you have 12 apples and give half to your sister, how many does she get?",
    answer: 6,
    choices: [5, 6, 7, 8],
    hint: "What is half of 12?",
    explanation: "Half of 12 = 6 apples for your sister!",
    vedicTrick: {
      name: "Half and Double",
      steps: ["Half means divide by 2", "12 ÷ 2 = 6", "6 + 6 = 12"],
    },
  },

  // ========== GRADE 2: Near 10 Addition ==========
  {
    id: "near10-1",
    skillId: "add-near-10",
    difficulty: 2,
    question: "8 + 7 = ?",
    answer: 15,
    choices: [13, 14, 15, 16],
    hint: "Make 10 first: 8 + 2 = 10, then add the rest",
    explanation: "8 + 7 = 8 + 2 + 5 = 10 + 5 = 15",
    vedicTrick: {
      name: "Make 10 Strategy",
      steps: ["Break 7 into 2 + 5", "8 + 2 = 10 (make 10 first!)", "10 + 5 = 15"],
    },
  },
  {
    id: "near10-2",
    skillId: "add-near-10",
    difficulty: 2,
    question: "9 + 6 = ?",
    answer: 15,
    choices: [13, 14, 15, 16],
    hint: "9 needs just 1 to make 10",
    explanation: "9 + 6 = 9 + 1 + 5 = 10 + 5 = 15",
    vedicTrick: {
      name: "Make 10 Strategy",
      steps: ["Break 6 into 1 + 5", "9 + 1 = 10", "10 + 5 = 15"],
    },
  },
  {
    id: "near10-3",
    skillId: "add-near-10",
    difficulty: 2,
    question: "7 + 8 = ?",
    answer: 15,
    choices: [13, 14, 15, 16],
    hint: "Make 10 first using 7 + 3",
    explanation: "7 + 8 = 7 + 3 + 5 = 10 + 5 = 15",
    vedicTrick: {
      name: "Make 10 Strategy",
      steps: ["Break 8 into 3 + 5", "7 + 3 = 10", "10 + 5 = 15"],
    },
  },

  // ========== GRADE 2: Multiply by 10 ==========
  {
    id: "mult10-1",
    skillId: "multiply-by-10",
    difficulty: 1,
    question: "6 × 10 = ?",
    answer: 60,
    choices: [16, 50, 60, 66],
    hint: "Just add a 0!",
    explanation: "Multiplying by 10 means adding a 0 to the end!",
    vedicTrick: {
      name: "Multiply by 10",
      steps: ["When multiplying by 10, just add a 0!", "6 → 60", "It's that easy!"],
    },
  },
  {
    id: "mult10-2",
    skillId: "multiply-by-10",
    difficulty: 1,
    question: "9 × 10 = ?",
    answer: 90,
    choices: [19, 80, 90, 99],
    hint: "Add a 0 to the number!",
    explanation: "9 × 10 = 90 (just add 0)",
    vedicTrick: {
      name: "Multiply by 10",
      steps: ["9 × 10 = ?", "Add a 0 to 9", "Answer: 90"],
    },
  },
  {
    id: "mult10-3",
    skillId: "multiply-by-10",
    difficulty: 2,
    question: "12 × 10 = ?",
    answer: 120,
    choices: [22, 102, 120, 112],
    hint: "Add a 0 to 12!",
    explanation: "12 × 10 = 120",
    vedicTrick: {
      name: "Multiply by 10",
      steps: ["This works for any number!", "12 → 120", "Just add that 0!"],
    },
  },

  // ========== GRADE 2: Multiply by 5 ==========
  {
    id: "mult5-1",
    skillId: "multiply-by-5",
    difficulty: 2,
    question: "8 × 5 = ?",
    answer: 40,
    choices: [35, 40, 45, 50],
    hint: "Multiply by 10, then take half!",
    explanation: "8 × 5 = (8 × 10) ÷ 2 = 80 ÷ 2 = 40",
    vedicTrick: {
      name: "Multiply by 5",
      steps: [
        "Multiply by 10 first: 8 × 10 = 80",
        "Take half: 80 ÷ 2 = 40",
        "5 is half of 10, so multiply by 10 and halve!",
      ],
    },
  },
  {
    id: "mult5-2",
    skillId: "multiply-by-5",
    difficulty: 2,
    question: "6 × 5 = ?",
    answer: 30,
    choices: [25, 30, 35, 40],
    hint: "Multiply by 10, then halve!",
    explanation: "6 × 5 = (6 × 10) ÷ 2 = 60 ÷ 2 = 30",
    vedicTrick: {
      name: "Multiply by 5",
      steps: ["6 × 10 = 60", "60 ÷ 2 = 30", "Quick way to multiply by 5!"],
    },
  },
  {
    id: "mult5-3",
    skillId: "multiply-by-5",
    difficulty: 2,
    question: "14 × 5 = ?",
    answer: 70,
    choices: [60, 65, 70, 75],
    hint: "Multiply by 10, then divide by 2",
    explanation: "14 × 5 = (14 × 10) ÷ 2 = 140 ÷ 2 = 70",
    vedicTrick: {
      name: "Multiply by 5",
      steps: ["14 × 10 = 140", "140 ÷ 2 = 70", "Works for any number!"],
    },
  },

  // ========== GRADE 2: Skip Counting ==========
  {
    id: "skip-1",
    skillId: "skip-count",
    difficulty: 1,
    question: "Count by 5s: 5, 10, 15, ?",
    answer: 20,
    choices: [16, 18, 20, 25],
    hint: "What comes after 15 when counting by 5s?",
    explanation: "Counting by 5s: the next number is 20!",
    vedicTrick: {
      name: "Skip Counting by 5s",
      steps: ["5s always end in 5 or 0!", "5, 10, 15, 20, 25...", "The pattern alternates: 5, 0, 5, 0..."],
    },
  },
  {
    id: "skip-2",
    skillId: "skip-count",
    difficulty: 1,
    question: "Count by 2s: 6, 8, 10, ?",
    answer: 12,
    choices: [11, 12, 13, 14],
    hint: "Add 2 to 10",
    explanation: "Counting by 2s: 10 + 2 = 12!",
    vedicTrick: {
      name: "Skip Counting by 2s",
      steps: ["Add 2 each time!", "6, 8, 10, 12, 14...", "These are all even numbers!"],
    },
  },

  // ========== GRADE 3: Multiply by 11 ==========
  {
    id: "mult11-1",
    skillId: "multiply-by-11",
    difficulty: 3,
    question: "35 × 11 = ?",
    answer: 385,
    choices: [375, 385, 395, 405],
    hint: "Put the sum of the digits in the middle!",
    explanation: "35 × 11: Put 3+5=8 in the middle → 385",
    vedicTrick: {
      name: "Multiply by 11",
      steps: ["Write the two digits with space: 3 _ 5", "Add the digits: 3 + 5 = 8", "Put 8 in the middle: 385"],
    },
  },
  {
    id: "mult11-2",
    skillId: "multiply-by-11",
    difficulty: 3,
    question: "72 × 11 = ?",
    answer: 792,
    choices: [782, 792, 802, 772],
    hint: "Add the digits and put the sum in the middle!",
    explanation: "72 × 11: Put 7+2=9 in the middle → 792",
    vedicTrick: {
      name: "Multiply by 11",
      steps: ["Write: 7 _ 2", "Add: 7 + 2 = 9", "Result: 792"],
    },
  },
  {
    id: "mult11-3",
    skillId: "multiply-by-11",
    difficulty: 4,
    question: "86 × 11 = ?",
    answer: 946,
    choices: [936, 946, 956, 8146],
    hint: "When the middle sum is 10+, carry over!",
    explanation: "86 × 11: 8+6=14, carry the 1 → (8+1)46 = 946",
    vedicTrick: {
      name: "Multiply by 11 (with carry)",
      steps: ["8 + 6 = 14 (double digit!)", "Put 4 in the middle, carry 1 to the left", "8 + 1 = 9, so answer is 946"],
    },
  },
  {
    id: "mult11-4",
    skillId: "multiply-by-11",
    difficulty: 3,
    question: "45 × 11 = ?",
    answer: 495,
    choices: [455, 485, 495, 505],
    hint: "4 + 5 = 9, put 9 in the middle",
    explanation: "45 × 11: 4_5 → put 9 in middle → 495",
    vedicTrick: {
      name: "Multiply by 11",
      steps: ["Write: 4 _ 5", "Add: 4 + 5 = 9", "Result: 495"],
    },
  },

  // ========== GRADE 3: Divide by 5 ==========
  {
    id: "div5-1",
    skillId: "divide-by-5",
    difficulty: 3,
    question: "45 ÷ 5 = ?",
    answer: 9,
    choices: [7, 8, 9, 10],
    hint: "Double the number, then divide by 10!",
    explanation: "45 ÷ 5 = (45 × 2) ÷ 10 = 90 ÷ 10 = 9",
    vedicTrick: {
      name: "Divide by 5",
      steps: ["Double the number: 45 × 2 = 90", "Divide by 10: 90 ÷ 10 = 9", "Dividing by 5 = doubling then ÷10!"],
    },
  },
  {
    id: "div5-2",
    skillId: "divide-by-5",
    difficulty: 3,
    question: "65 ÷ 5 = ?",
    answer: 13,
    choices: [11, 12, 13, 14],
    hint: "Double it, then drop the 0!",
    explanation: "65 ÷ 5 = (65 × 2) ÷ 10 = 130 ÷ 10 = 13",
    vedicTrick: {
      name: "Divide by 5",
      steps: ["Double: 65 × 2 = 130", "Divide by 10: 130 ÷ 10 = 13", "The trick: multiply by 2, divide by 10!"],
    },
  },
  {
    id: "div5-3",
    skillId: "divide-by-5",
    difficulty: 3,
    question: "85 ÷ 5 = ?",
    answer: 17,
    choices: [15, 16, 17, 18],
    hint: "Double 85, then divide by 10",
    explanation: "85 ÷ 5 = (85 × 2) ÷ 10 = 170 ÷ 10 = 17",
    vedicTrick: {
      name: "Divide by 5",
      steps: ["85 × 2 = 170", "170 ÷ 10 = 17", "Fast division by 5!"],
    },
  },

  // ========== GRADE 3: Square Numbers Ending in 5 ==========
  {
    id: "sq5-1",
    skillId: "square-ends-5",
    difficulty: 3,
    question: "25 × 25 = ?",
    answer: 625,
    choices: [525, 575, 625, 675],
    hint: "Multiply tens digit by next number, then add 25!",
    explanation: "25²: 2 × 3 = 6, then add 25 → 625",
    vedicTrick: {
      name: "Square Numbers Ending in 5",
      steps: ["Take the tens digit: 2", "Multiply by next number: 2 × 3 = 6", "Add 25 at the end: 625"],
    },
  },
  {
    id: "sq5-2",
    skillId: "square-ends-5",
    difficulty: 3,
    question: "35 × 35 = ?",
    answer: 1225,
    choices: [1125, 1225, 1325, 1025],
    hint: "3 × 4 = 12, then add 25",
    explanation: "35²: 3 × 4 = 12, add 25 → 1225",
    vedicTrick: {
      name: "Square Numbers Ending in 5",
      steps: ["Tens digit is 3", "3 × 4 = 12", "Add 25: 1225"],
    },
  },
  {
    id: "sq5-3",
    skillId: "square-ends-5",
    difficulty: 3,
    question: "55 × 55 = ?",
    answer: 3025,
    choices: [2925, 3025, 3125, 3055],
    hint: "5 × 6 = 30, then add 25",
    explanation: "55²: 5 × 6 = 30, add 25 → 3025",
    vedicTrick: {
      name: "Square Numbers Ending in 5",
      steps: ["Tens digit is 5", "5 × 6 = 30", "Add 25: 3025"],
    },
  },
  {
    id: "sq5-4",
    skillId: "square-ends-5",
    difficulty: 4,
    question: "85 × 85 = ?",
    answer: 7225,
    choices: [7025, 7125, 7225, 7325],
    hint: "8 × 9 = 72, then add 25",
    explanation: "85²: 8 × 9 = 72, add 25 → 7225",
    vedicTrick: {
      name: "Square Numbers Ending in 5",
      steps: ["Tens digit is 8", "8 × 9 = 72", "Add 25: 7225"],
    },
  },

  // ========== GRADE 3: Same Tens, Ones Add to 10 ==========
  {
    id: "same10-1",
    skillId: "same-tens-add-10",
    difficulty: 3,
    question: "42 × 48 = ?",
    answer: 2016,
    choices: [1916, 2016, 2116, 2216],
    hint: "Tens same (4), ones add to 10 (2+8). Use the trick!",
    explanation: "42 × 48: 4×5=20, 2×8=16 → 2016",
    vedicTrick: {
      name: "Same Tens, Add to 10",
      steps: ["Tens digit × (tens digit + 1): 4 × 5 = 20", "Ones digits multiplied: 2 × 8 = 16", "Put together: 2016"],
    },
  },
  {
    id: "same10-2",
    skillId: "same-tens-add-10",
    difficulty: 3,
    question: "63 × 67 = ?",
    answer: 4221,
    choices: [4121, 4221, 4321, 4021],
    hint: "6×7=42, 3×7=21",
    explanation: "63 × 67: 6×7=42, 3×7=21 → 4221",
    vedicTrick: {
      name: "Same Tens, Add to 10",
      steps: ["6 × 7 = 42", "3 × 7 = 21", "Answer: 4221"],
    },
  },
  {
    id: "same10-3",
    skillId: "same-tens-add-10",
    difficulty: 3,
    question: "71 × 79 = ?",
    answer: 5609,
    choices: [5509, 5609, 5709, 5619],
    hint: "7×8=56, 1×9=09",
    explanation: "71 × 79: 7×8=56, 1×9=09 → 5609",
    vedicTrick: {
      name: "Same Tens, Add to 10",
      steps: ["7 × 8 = 56", "1 × 9 = 9 (write as 09)", "Answer: 5609"],
    },
  },
  {
    id: "same10-4",
    skillId: "same-tens-add-10",
    difficulty: 4,
    question: "84 × 86 = ?",
    answer: 7224,
    choices: [7124, 7224, 7324, 7234],
    hint: "8×9=72, 4×6=24",
    explanation: "84 × 86: 8×9=72, 4×6=24 → 7224",
    vedicTrick: {
      name: "Same Tens, Add to 10",
      steps: ["8 × 9 = 72", "4 × 6 = 24", "Answer: 7224"],
    },
  },

  // ========== GRADE 4: Numbers Near 100 (Below) ==========
  {
    id: "near100b-1",
    skillId: "near-100-below",
    difficulty: 4,
    question: "97 × 96 = ?",
    answer: 9312,
    choices: [9212, 9312, 9412, 9302],
    hint: "Differences from 100: -3, -4. Cross subtract, then multiply!",
    explanation: "97×96: (97-4)=93, (3×4)=12 → 9312",
    vedicTrick: {
      name: "Numbers Near 100 (Below)",
      steps: [
        "97 is 3 below 100, 96 is 4 below 100",
        "Cross subtract: 97 - 4 = 93",
        "Multiply deficits: 3 × 4 = 12",
        "Answer: 9312",
      ],
    },
  },
  {
    id: "near100b-2",
    skillId: "near-100-below",
    difficulty: 4,
    question: "94 × 95 = ?",
    answer: 8930,
    choices: [8830, 8930, 9030, 8920],
    hint: "94-5=89, 6×5=30",
    explanation: "94×95: (94-5)=89, (6×5)=30 → 8930",
    vedicTrick: {
      name: "Numbers Near 100 (Below)",
      steps: [
        "94 is 6 below 100, 95 is 5 below 100",
        "Cross subtract: 94 - 5 = 89",
        "Multiply deficits: 6 × 5 = 30",
        "Answer: 8930",
      ],
    },
  },
  {
    id: "near100b-3",
    skillId: "near-100-below",
    difficulty: 4,
    question: "98 × 97 = ?",
    answer: 9506,
    choices: [9406, 9506, 9606, 9516],
    hint: "98-3=95, 2×3=06",
    explanation: "98×97: (98-3)=95, (2×3)=06 → 9506",
    vedicTrick: {
      name: "Numbers Near 100 (Below)",
      steps: [
        "98 is 2 below 100, 97 is 3 below 100",
        "Cross subtract: 98 - 3 = 95",
        "Multiply deficits: 2 × 3 = 6 (write as 06)",
        "Answer: 9506",
      ],
    },
  },
  {
    id: "near100b-4",
    skillId: "near-100-below",
    difficulty: 5,
    question: "91 × 93 = ?",
    answer: 8463,
    choices: [8363, 8463, 8563, 8453],
    hint: "91-7=84, 9×7=63",
    explanation: "91×93: (91-7)=84, (9×7)=63 → 8463",
    vedicTrick: {
      name: "Numbers Near 100 (Below)",
      steps: [
        "91 is 9 below 100, 93 is 7 below 100",
        "Cross subtract: 91 - 7 = 84",
        "Multiply deficits: 9 × 7 = 63",
        "Answer: 8463",
      ],
    },
  },
  {
    id: "near100b-5",
    skillId: "near-100-below",
    difficulty: 4,
    question: "99 × 98 = ?",
    answer: 9702,
    choices: [9602, 9702, 9802, 9712],
    hint: "99-2=97, 1×2=02",
    explanation: "99×98: (99-2)=97, (1×2)=02 → 9702",
    vedicTrick: {
      name: "Numbers Near 100 (Below)",
      steps: [
        "99 is 1 below 100, 98 is 2 below 100",
        "Cross subtract: 99 - 2 = 97",
        "Multiply deficits: 1 × 2 = 2 (write as 02)",
        "Answer: 9702",
      ],
    },
  },
  {
    id: "near100b-6",
    skillId: "near-100-below",
    difficulty: 4,
    question: "96 × 95 = ?",
    answer: 9120,
    choices: [9020, 9120, 9220, 9110],
    hint: "96-5=91, 4×5=20",
    explanation: "96×95: (96-5)=91, (4×5)=20 → 9120",
    vedicTrick: {
      name: "Numbers Near 100 (Below)",
      steps: [
        "96 is 4 below 100, 95 is 5 below 100",
        "Cross subtract: 96 - 5 = 91",
        "Multiply deficits: 4 × 5 = 20",
        "Answer: 9120",
      ],
    },
  },
  {
    id: "near100b-7",
    skillId: "near-100-below",
    difficulty: 4,
    question: "93 × 94 = ?",
    answer: 8742,
    choices: [8642, 8742, 8842, 8732],
    hint: "93-6=87, 7×6=42",
    explanation: "93×94: (93-6)=87, (7×6)=42 → 8742",
    vedicTrick: {
      name: "Numbers Near 100 (Below)",
      steps: [
        "93 is 7 below 100, 94 is 6 below 100",
        "Cross subtract: 93 - 6 = 87",
        "Multiply deficits: 7 × 6 = 42",
        "Answer: 8742",
      ],
    },
  },
  {
    id: "near100b-8",
    skillId: "near-100-below",
    difficulty: 5,
    question: "92 × 91 = ?",
    answer: 8372,
    choices: [8272, 8372, 8472, 8362],
    hint: "92-9=83, 8×9=72",
    explanation: "92×91: (92-9)=83, (8×9)=72 → 8372",
    vedicTrick: {
      name: "Numbers Near 100 (Below)",
      steps: [
        "92 is 8 below 100, 91 is 9 below 100",
        "Cross subtract: 92 - 9 = 83",
        "Multiply deficits: 8 × 9 = 72",
        "Answer: 8372",
      ],
    },
  },
  {
    id: "near100b-9",
    skillId: "near-100-below",
    difficulty: 5,
    question: "95 × 93 = ?",
    answer: 8835,
    choices: [8735, 8835, 8935, 8825],
    hint: "95-7=88, 5×7=35",
    explanation: "95×93: (95-7)=88, (5×7)=35 → 8835",
    vedicTrick: {
      name: "Numbers Near 100 (Below)",
      steps: [
        "95 is 5 below 100, 93 is 7 below 100",
        "Cross subtract: 95 - 7 = 88",
        "Multiply deficits: 5 × 7 = 35",
        "Answer: 8835",
      ],
    },
  },
  {
    id: "near100b-10",
    skillId: "near-100-below",
    difficulty: 5,
    question: "90 × 92 = ?",
    answer: 8280,
    choices: [8180, 8280, 8380, 8270],
    hint: "90-8=82, 10×8=80",
    explanation: "90×92: (90-8)=82, (10×8)=80 → 8280",
    vedicTrick: {
      name: "Numbers Near 100 (Below)",
      steps: [
        "90 is 10 below 100, 92 is 8 below 100",
        "Cross subtract: 90 - 8 = 82",
        "Multiply deficits: 10 × 8 = 80",
        "Answer: 8280",
      ],
    },
  },
  {
    id: "near100b-11",
    skillId: "near-100-below",
    difficulty: 4,
    question: "99 × 99 = ?",
    answer: 9801,
    choices: [9701, 9801, 9901, 9811],
    hint: "99-1=98, 1×1=01",
    explanation: "99×99: (99-1)=98, (1×1)=01 → 9801",
    vedicTrick: {
      name: "Numbers Near 100 (Below)",
      steps: [
        "99 is 1 below 100",
        "Cross subtract: 99 - 1 = 98",
        "Multiply deficits: 1 × 1 = 1 (write as 01)",
        "Answer: 9801",
      ],
    },
  },
  {
    id: "near100b-12",
    skillId: "near-100-below",
    difficulty: 5,
    question: "89 × 91 = ?",
    answer: 8099,
    choices: [7999, 8099, 8199, 8089],
    hint: "89-9=80, 11×9=99",
    explanation: "89×91: (89-9)=80, (11×9)=99 → 8099",
    vedicTrick: {
      name: "Numbers Near 100 (Below)",
      steps: [
        "89 is 11 below 100, 91 is 9 below 100",
        "Cross subtract: 89 - 9 = 80",
        "Multiply deficits: 11 × 9 = 99",
        "Answer: 8099",
      ],
    },
  },

  // ========== GRADE 4: Numbers Near 100 (Above) ==========
  {
    id: "near100a-1",
    skillId: "near-100-above",
    difficulty: 4,
    question: "103 × 104 = ?",
    answer: 10712,
    choices: [10612, 10712, 10812, 10702],
    hint: "Add the excess, then multiply excesses!",
    explanation: "103×104: (103+4)=107, (3×4)=12 → 10712",
    vedicTrick: {
      name: "Numbers Near 100 (Above)",
      steps: [
        "103 is 3 above 100, 104 is 4 above 100",
        "Cross add: 103 + 4 = 107",
        "Multiply excesses: 3 × 4 = 12",
        "Answer: 10712",
      ],
    },
  },
  {
    id: "near100a-2",
    skillId: "near-100-above",
    difficulty: 4,
    question: "101 × 108 = ?",
    answer: 10908,
    choices: [10808, 10908, 11008, 10918],
    hint: "101+8=109, 1×8=08",
    explanation: "101×108: (101+8)=109, (1×8)=08 → 10908",
    vedicTrick: {
      name: "Numbers Near 100 (Above)",
      steps: [
        "101 is 1 above 100, 108 is 8 above 100",
        "Cross add: 101 + 8 = 109",
        "Multiply excesses: 1 × 8 = 8 (write as 08)",
        "Answer: 10908",
      ],
    },
  },
  {
    id: "near100a-3",
    skillId: "near-100-above",
    difficulty: 4,
    question: "105 × 106 = ?",
    answer: 11130,
    choices: [11030, 11130, 11230, 11120],
    hint: "105+6=111, 5×6=30",
    explanation: "105×106: (105+6)=111, (5×6)=30 → 11130",
    vedicTrick: {
      name: "Numbers Near 100 (Above)",
      steps: [
        "105 is 5 above 100, 106 is 6 above 100",
        "Cross add: 105 + 6 = 111",
        "Multiply excesses: 5 × 6 = 30",
        "Answer: 11130",
      ],
    },
  },
  {
    id: "near100a-4",
    skillId: "near-100-above",
    difficulty: 5,
    question: "107 × 109 = ?",
    answer: 11663,
    choices: [11563, 11663, 11763, 11653],
    hint: "107+9=116, 7×9=63",
    explanation: "107×109: (107+9)=116, (7×9)=63 → 11663",
    vedicTrick: {
      name: "Numbers Near 100 (Above)",
      steps: [
        "107 is 7 above 100, 109 is 9 above 100",
        "Cross add: 107 + 9 = 116",
        "Multiply excesses: 7 × 9 = 63",
        "Answer: 11663",
      ],
    },
  },
  {
    id: "near100a-5",
    skillId: "near-100-above",
    difficulty: 4,
    question: "102 × 103 = ?",
    answer: 10506,
    choices: [10406, 10506, 10606, 10516],
    hint: "102+3=105, 2×3=06",
    explanation: "102×103: (102+3)=105, (2×3)=06 → 10506",
    vedicTrick: {
      name: "Numbers Near 100 (Above)",
      steps: [
        "102 is 2 above 100, 103 is 3 above 100",
        "Cross add: 102 + 3 = 105",
        "Multiply excesses: 2 × 3 = 6 (write as 06)",
        "Answer: 10506",
      ],
    },
  },
  {
    id: "near100a-6",
    skillId: "near-100-above",
    difficulty: 4,
    question: "104 × 105 = ?",
    answer: 10920,
    choices: [10820, 10920, 11020, 10910],
    hint: "104+5=109, 4×5=20",
    explanation: "104×105: (104+5)=109, (4×5)=20 → 10920",
    vedicTrick: {
      name: "Numbers Near 100 (Above)",
      steps: [
        "104 is 4 above 100, 105 is 5 above 100",
        "Cross add: 104 + 5 = 109",
        "Multiply excesses: 4 × 5 = 20",
        "Answer: 10920",
      ],
    },
  },
  {
    id: "near100a-7",
    skillId: "near-100-above",
    difficulty: 4,
    question: "106 × 107 = ?",
    answer: 11342,
    choices: [11242, 11342, 11442, 11332],
    hint: "106+7=113, 6×7=42",
    explanation: "106×107: (106+7)=113, (6×7)=42 → 11342",
    vedicTrick: {
      name: "Numbers Near 100 (Above)",
      steps: [
        "106 is 6 above 100, 107 is 7 above 100",
        "Cross add: 106 + 7 = 113",
        "Multiply excesses: 6 × 7 = 42",
        "Answer: 11342",
      ],
    },
  },
  {
    id: "near100a-8",
    skillId: "near-100-above",
    difficulty: 5,
    question: "108 × 109 = ?",
    answer: 11772,
    choices: [11672, 11772, 11872, 11762],
    hint: "108+9=117, 8×9=72",
    explanation: "108×109: (108+9)=117, (8×9)=72 → 11772",
    vedicTrick: {
      name: "Numbers Near 100 (Above)",
      steps: [
        "108 is 8 above 100, 109 is 9 above 100",
        "Cross add: 108 + 9 = 117",
        "Multiply excesses: 8 × 9 = 72",
        "Answer: 11772",
      ],
    },
  },
  {
    id: "near100a-9",
    skillId: "near-100-above",
    difficulty: 5,
    question: "103 × 107 = ?",
    answer: 11021,
    choices: [10921, 11021, 11121, 11011],
    hint: "103+7=110, 3×7=21",
    explanation: "103×107: (103+7)=110, (3×7)=21 → 11021",
    vedicTrick: {
      name: "Numbers Near 100 (Above)",
      steps: [
        "103 is 3 above 100, 107 is 7 above 100",
        "Cross add: 103 + 7 = 110",
        "Multiply excesses: 3 × 7 = 21",
        "Answer: 11021",
      ],
    },
  },
  {
    id: "near100a-10",
    skillId: "near-100-above",
    difficulty: 5,
    question: "110 × 105 = ?",
    answer: 11550,
    choices: [11450, 11550, 11650, 11540],
    hint: "110+5=115, 10×5=50",
    explanation: "110×105: (110+5)=115, (10×5)=50 → 11550",
    vedicTrick: {
      name: "Numbers Near 100 (Above)",
      steps: [
        "110 is 10 above 100, 105 is 5 above 100",
        "Cross add: 110 + 5 = 115",
        "Multiply excesses: 10 × 5 = 50",
        "Answer: 11550",
      ],
    },
  },
  {
    id: "near100a-11",
    skillId: "near-100-above",
    difficulty: 4,
    question: "101 × 101 = ?",
    answer: 10201,
    choices: [10101, 10201, 10301, 10211],
    hint: "101+1=102, 1×1=01",
    explanation: "101×101: (101+1)=102, (1×1)=01 → 10201",
    vedicTrick: {
      name: "Numbers Near 100 (Above)",
      steps: [
        "101 is 1 above 100",
        "Cross add: 101 + 1 = 102",
        "Multiply excesses: 1 × 1 = 1 (write as 01)",
        "Answer: 10201",
      ],
    },
  },
  {
    id: "near100a-12",
    skillId: "near-100-above",
    difficulty: 5,
    question: "112 × 108 = ?",
    answer: 12096,
    choices: [11996, 12096, 12196, 12086],
    hint: "112+8=120, 12×8=96",
    explanation: "112×108: (112+8)=120, (12×8)=96 → 12096",
    vedicTrick: {
      name: "Numbers Near 100 (Above)",
      steps: [
        "112 is 12 above 100, 108 is 8 above 100",
        "Cross add: 112 + 8 = 120",
        "Multiply excesses: 12 × 8 = 96",
        "Answer: 12096",
      ],
    },
  },

  // ========== GRADE 4: Cross Multiplication ==========
  {
    id: "cross-1",
    skillId: "cross-multiply",
    difficulty: 4,
    question: "23 × 12 = ?",
    answer: 276,
    choices: [266, 276, 286, 296],
    hint: "Cross multiply: (2×1), (2×2+3×1), (3×2)",
    explanation: "23×12: 2×1=2, (2×2)+(3×1)=7, 3×2=6 → 276",
    vedicTrick: {
      name: "Cross Multiplication",
      steps: [
        "Multiply left digits: 2 × 1 = 2",
        "Cross multiply and add: (2×2) + (3×1) = 4 + 3 = 7",
        "Multiply right digits: 3 × 2 = 6",
        "Answer: 276",
      ],
    },
  },
  {
    id: "cross-2",
    skillId: "cross-multiply",
    difficulty: 4,
    question: "31 × 21 = ?",
    answer: 651,
    choices: [641, 651, 661, 671],
    hint: "Cross multiply step by step",
    explanation: "31×21: 3×2=6, (3×1)+(1×2)=5, 1×1=1 → 651",
    vedicTrick: {
      name: "Cross Multiplication",
      steps: ["Left: 3 × 2 = 6", "Cross: (3×1) + (1×2) = 3 + 2 = 5", "Right: 1 × 1 = 1", "Answer: 651"],
    },
  },
  {
    id: "cross-3",
    skillId: "cross-multiply",
    difficulty: 5,
    question: "24 × 13 = ?",
    answer: 312,
    choices: [302, 312, 322, 332],
    hint: "Cross multiply: 2×1=2, (2×3)+(4×1)=10, 4×3=12",
    explanation: "24×13: Handle carries → 312",
    vedicTrick: {
      name: "Cross Multiplication (with carry)",
      steps: [
        "Right: 4 × 3 = 12, write 2, carry 1",
        "Cross: (2×3) + (4×1) = 6 + 4 = 10, +1 = 11, write 1, carry 1",
        "Left: 2 × 1 = 2, +1 = 3",
        "Answer: 312",
      ],
    },
  },
  {
    id: "cross-4",
    skillId: "cross-multiply",
    difficulty: 4,
    question: "32 × 11 = ?",
    answer: 352,
    choices: [342, 352, 362, 372],
    hint: "Cross multiply systematically",
    explanation: "32×11: 3×1=3, (3×1)+(2×1)=5, 2×1=2 → 352",
    vedicTrick: {
      name: "Cross Multiplication",
      steps: ["Left: 3 × 1 = 3", "Cross: (3×1) + (2×1) = 3 + 2 = 5", "Right: 2 × 1 = 2", "Answer: 352"],
    },
  },
  {
    id: "cross-5",
    skillId: "cross-multiply",
    difficulty: 4,
    question: "22 × 13 = ?",
    answer: 286,
    choices: [276, 286, 296, 306],
    hint: "Use cross multiplication",
    explanation: "22×13: 2×1=2, (2×3)+(2×1)=8, 2×3=6 → 286",
    vedicTrick: {
      name: "Cross Multiplication",
      steps: ["Left: 2 × 1 = 2", "Cross: (2×3) + (2×1) = 6 + 2 = 8", "Right: 2 × 3 = 6", "Answer: 286"],
    },
  },
  {
    id: "cross-6",
    skillId: "cross-multiply",
    difficulty: 4,
    question: "41 × 12 = ?",
    answer: 492,
    choices: [482, 492, 502, 512],
    hint: "Cross multiply left, middle, right",
    explanation: "41×12: 4×1=4, (4×2)+(1×1)=9, 1×2=2 → 492",
    vedicTrick: {
      name: "Cross Multiplication",
      steps: ["Left: 4 × 1 = 4", "Cross: (4×2) + (1×1) = 8 + 1 = 9", "Right: 1 × 2 = 2", "Answer: 492"],
    },
  },
  {
    id: "cross-7",
    skillId: "cross-multiply",
    difficulty: 5,
    question: "33 × 22 = ?",
    answer: 726,
    choices: [716, 726, 736, 746],
    hint: "Cross multiplication with carries",
    explanation: "33×22: 3×2=6, (3×2)+(3×2)=12, 3×2=6 → 726",
    vedicTrick: {
      name: "Cross Multiplication",
      steps: [
        "Left: 3 × 2 = 6",
        "Cross: (3×2) + (3×2) = 6 + 6 = 12, write 2, carry 1",
        "Right: 3 × 2 = 6, +1 = 7",
        "Answer: 726",
      ],
    },
  },
  {
    id: "cross-8",
    skillId: "cross-multiply",
    difficulty: 5,
    question: "34 × 21 = ?",
    answer: 714,
    choices: [704, 714, 724, 734],
    hint: "Use the cross method",
    explanation: "34×21: 3×2=6, (3×1)+(4×2)=11, 4×1=4 → 714",
    vedicTrick: {
      name: "Cross Multiplication",
      steps: [
        "Left: 3 × 2 = 6",
        "Cross: (3×1) + (4×2) = 3 + 8 = 11, write 1, carry 1",
        "Right: 4 × 1 = 4, +1 (total becomes 7,1,4)",
        "Answer: 714",
      ],
    },
  },
  {
    id: "cross-9",
    skillId: "cross-multiply",
    difficulty: 4,
    question: "42 × 11 = ?",
    answer: 462,
    choices: [452, 462, 472, 482],
    hint: "Cross multiply",
    explanation: "42×11: 4×1=4, (4×1)+(2×1)=6, 2×1=2 → 462",
    vedicTrick: {
      name: "Cross Multiplication",
      steps: ["Left: 4 × 1 = 4", "Cross: (4×1) + (2×1) = 4 + 2 = 6", "Right: 2 × 1 = 2", "Answer: 462"],
    },
  },
  {
    id: "cross-10",
    skillId: "cross-multiply",
    difficulty: 4,
    question: "21 × 14 = ?",
    answer: 294,
    choices: [284, 294, 304, 314],
    hint: "Apply cross multiplication",
    explanation: "21×14: 2×1=2, (2×4)+(1×1)=9, 1×4=4 → 294",
    vedicTrick: {
      name: "Cross Multiplication",
      steps: ["Left: 2 × 1 = 2", "Cross: (2×4) + (1×1) = 8 + 1 = 9", "Right: 1 × 4 = 4", "Answer: 294"],
    },
  },

  // ========== GRADE 4: Divide Large Numbers by 5 ==========
  {
    id: "divlg5-1",
    skillId: "divide-large-by-5",
    difficulty: 4,
    question: "235 ÷ 5 = ?",
    answer: 47,
    choices: [45, 46, 47, 48],
    hint: "Double the number, divide by 10!",
    explanation: "235 ÷ 5 = (235 × 2) ÷ 10 = 470 ÷ 10 = 47",
    vedicTrick: {
      name: "Divide by 5 (Large Numbers)",
      steps: ["Double: 235 × 2 = 470", "Divide by 10: 470 ÷ 10 = 47", "Works for any number!"],
    },
  },
  {
    id: "divlg5-2",
    skillId: "divide-large-by-5",
    difficulty: 4,
    question: "425 ÷ 5 = ?",
    answer: 85,
    choices: [80, 83, 85, 90],
    hint: "Double, then ÷10",
    explanation: "425 ÷ 5 = (425 × 2) ÷ 10 = 850 ÷ 10 = 85",
    vedicTrick: {
      name: "Divide by 5 (Large Numbers)",
      steps: ["425 × 2 = 850", "850 ÷ 10 = 85", "Doubling makes ÷5 easy!"],
    },
  },
  {
    id: "divlg5-3",
    skillId: "divide-large-by-5",
    difficulty: 5,
    question: "1275 ÷ 5 = ?",
    answer: 255,
    choices: [245, 250, 255, 260],
    hint: "1275 × 2 = 2550, then ÷10",
    explanation: "1275 ÷ 5 = (1275 × 2) ÷ 10 = 2550 ÷ 10 = 255",
    vedicTrick: {
      name: "Divide by 5 (Large Numbers)",
      steps: ["1275 × 2 = 2550", "2550 ÷ 10 = 255", "The trick: multiply by 2, divide by 10!"],
    },
  },
  {
    id: "divlg5-4",
    skillId: "divide-large-by-5",
    difficulty: 4,
    question: "315 ÷ 5 = ?",
    answer: 63,
    choices: [61, 62, 63, 64],
    hint: "Double then divide by 10",
    explanation: "315 ÷ 5 = (315 × 2) ÷ 10 = 630 ÷ 10 = 63",
    vedicTrick: {
      name: "Divide by 5 (Large Numbers)",
      steps: ["315 × 2 = 630", "630 ÷ 10 = 63", "Easy division!"],
    },
  },
  {
    id: "divlg5-5",
    skillId: "divide-large-by-5",
    difficulty: 4,
    question: "540 ÷ 5 = ?",
    answer: 108,
    choices: [106, 107, 108, 109],
    hint: "Double and divide by 10",
    explanation: "540 ÷ 5 = (540 × 2) ÷ 10 = 1080 ÷ 10 = 108",
    vedicTrick: {
      name: "Divide by 5 (Large Numbers)",
      steps: ["540 × 2 = 1080", "1080 ÷ 10 = 108", "Quick and easy!"],
    },
  },
  {
    id: "divlg5-6",
    skillId: "divide-large-by-5",
    difficulty: 4,
    question: "685 ÷ 5 = ?",
    answer: 137,
    choices: [135, 136, 137, 138],
    hint: "Use the doubling trick",
    explanation: "685 ÷ 5 = (685 × 2) ÷ 10 = 1370 ÷ 10 = 137",
    vedicTrick: {
      name: "Divide by 5 (Large Numbers)",
      steps: ["685 × 2 = 1370", "1370 ÷ 10 = 137", "Vedic magic!"],
    },
  },
  {
    id: "divlg5-7",
    skillId: "divide-large-by-5",
    difficulty: 5,
    question: "935 ÷ 5 = ?",
    answer: 187,
    choices: [185, 186, 187, 188],
    hint: "Double first, then ÷10",
    explanation: "935 ÷ 5 = (935 × 2) ÷ 10 = 1870 ÷ 10 = 187",
    vedicTrick: {
      name: "Divide by 5 (Large Numbers)",
      steps: ["935 × 2 = 1870", "1870 ÷ 10 = 187", "Simple!"],
    },
  },
  {
    id: "divlg5-8",
    skillId: "divide-large-by-5",
    difficulty: 5,
    question: "1565 ÷ 5 = ?",
    answer: 313,
    choices: [311, 312, 313, 314],
    hint: "Double and divide by 10",
    explanation: "1565 ÷ 5 = (1565 × 2) ÷ 10 = 3130 ÷ 10 = 313",
    vedicTrick: {
      name: "Divide by 5 (Large Numbers)",
      steps: ["1565 × 2 = 3130", "3130 ÷ 10 = 313", "Works every time!"],
    },
  },
  {
    id: "divlg5-9",
    skillId: "divide-large-by-5",
    difficulty: 4,
    question: "780 ÷ 5 = ?",
    answer: 156,
    choices: [154, 155, 156, 157],
    hint: "Double the number first",
    explanation: "780 ÷ 5 = (780 × 2) ÷ 10 = 1560 ÷ 10 = 156",
    vedicTrick: {
      name: "Divide by 5 (Large Numbers)",
      steps: ["780 × 2 = 1560", "1560 ÷ 10 = 156", "So fast!"],
    },
  },
  {
    id: "divlg5-10",
    skillId: "divide-large-by-5",
    difficulty: 5,
    question: "2045 ÷ 5 = ?",
    answer: 409,
    choices: [407, 408, 409, 410],
    hint: "Use the doubling method",
    explanation: "2045 ÷ 5 = (2045 × 2) ÷ 10 = 4090 ÷ 10 = 409",
    vedicTrick: {
      name: "Divide by 5 (Large Numbers)",
      steps: ["2045 × 2 = 4090", "4090 ÷ 10 = 409", "Vedic shortcut!"],
    },
  },

  // ========== GRADE 4: Fractions & Decimals ==========
  {
    id: "frac-eq-1",
    skillId: "equivalent-fractions",
    difficulty: 3,
    question: "Which fraction is equivalent to 1/2?",
    answer: "2/4",
    choices: ["1/4", "2/4", "3/5", "1/3"],
    hint: "Multiply both numerator and denominator by 2",
    explanation: "1/2 = 2/4 (multiply top and bottom by 2)",
    vedicTrick: {
      name: "Equivalent Fractions",
      steps: [
        "To find equivalent fractions, multiply (or divide) both top and bottom by the same number",
        "1/2 × 2/2 = 2/4",
        "They represent the same amount!",
      ],
    },
  },
  {
    id: "frac-eq-2",
    skillId: "equivalent-fractions",
    difficulty: 3,
    question: "Which fraction equals 3/4?",
    answer: "6/8",
    choices: ["3/8", "6/8", "4/6", "9/16"],
    hint: "Multiply both parts by 2",
    explanation: "3/4 = 6/8 (multiply by 2/2)",
    vedicTrick: {
      name: "Equivalent Fractions",
      steps: ["3/4 × 2/2 = 6/8", "Same rule: multiply top and bottom equally"],
    },
  },
  {
    id: "frac-eq-3",
    skillId: "equivalent-fractions",
    difficulty: 4,
    question: "Simplify: 8/12 = ?",
    answer: "2/3",
    choices: ["2/3", "4/6", "1/2", "3/4"],
    hint: "Divide both by 4",
    explanation: "8/12 = 2/3 (divide both by 4)",
    vedicTrick: {
      name: "Simplifying Fractions",
      steps: ["Find the greatest common factor: 4", "8 ÷ 4 = 2", "12 ÷ 4 = 3", "Answer: 2/3"],
    },
  },
  {
    id: "frac-comp-1",
    skillId: "compare-fractions",
    difficulty: 3,
    question: "Which is greater: 2/3 or 3/4?",
    answer: "3/4",
    choices: ["2/3", "3/4", "equal"],
    hint: "Find a common denominator (12)",
    explanation: "2/3 = 8/12, 3/4 = 9/12, so 3/4 is greater",
    vedicTrick: {
      name: "Comparing Fractions",
      steps: ["Find common denominator: 12", "2/3 = 8/12", "3/4 = 9/12", "9 > 8, so 3/4 > 2/3"],
    },
  },
  {
    id: "frac-comp-2",
    skillId: "compare-fractions",
    difficulty: 3,
    question: "Which is smaller: 1/2 or 3/5?",
    answer: "1/2",
    choices: ["1/2", "3/5", "equal"],
    hint: "Convert to common denominator 10",
    explanation: "1/2 = 5/10, 3/5 = 6/10, so 1/2 is smaller",
    vedicTrick: {
      name: "Comparing Fractions",
      steps: ["Common denominator: 10", "1/2 = 5/10", "3/5 = 6/10", "5 < 6, so 1/2 < 3/5"],
    },
  },
  {
    id: "frac-dec-1",
    skillId: "fractions-decimals",
    difficulty: 3,
    question: "What is 1/2 as a decimal?",
    answer: "0.5",
    choices: ["0.2", "0.5", "0.25", "0.75"],
    hint: "1 divided by 2",
    explanation: "1 ÷ 2 = 0.5",
    vedicTrick: {
      name: "Fractions to Decimals",
      steps: ["Divide the numerator by denominator", "1 ÷ 2 = 0.5", "Half = 0.5"],
    },
  },
  {
    id: "frac-dec-2",
    skillId: "fractions-decimals",
    difficulty: 3,
    question: "What is 1/4 as a decimal?",
    answer: "0.25",
    choices: ["0.2", "0.25", "0.4", "0.5"],
    hint: "1 divided by 4",
    explanation: "1 ÷ 4 = 0.25",
    vedicTrick: {
      name: "Fractions to Decimals",
      steps: ["1 ÷ 4 = 0.25", "One quarter = 25 cents!"],
    },
  },
  {
    id: "frac-dec-3",
    skillId: "fractions-decimals",
    difficulty: 4,
    question: "What is 3/4 as a decimal?",
    answer: "0.75",
    choices: ["0.34", "0.65", "0.75", "0.85"],
    hint: "3 divided by 4",
    explanation: "3 ÷ 4 = 0.75",
    vedicTrick: {
      name: "Fractions to Decimals",
      steps: ["3 ÷ 4 = 0.75", "Three quarters = 75 cents!"],
    },
  },
  {
    id: "frac-add-1",
    skillId: "fractions-decimals",
    difficulty: 4,
    question: "1/4 + 1/4 = ?",
    answer: "1/2",
    choices: ["1/8", "2/8", "1/2", "2/4"],
    hint: "Add the numerators, keep denominator",
    explanation: "1/4 + 1/4 = 2/4 = 1/2",
    vedicTrick: {
      name: "Adding Fractions",
      steps: ["Same denominator, so add numerators", "1 + 1 = 2", "2/4 simplifies to 1/2"],
    },
  },
  {
    id: "frac-add-2",
    skillId: "fractions-decimals",
    difficulty: 4,
    question: "2/5 + 1/5 = ?",
    answer: "3/5",
    choices: ["3/10", "3/5", "1/5", "2/5"],
    hint: "Add numerators when denominators match",
    explanation: "2/5 + 1/5 = 3/5",
    vedicTrick: {
      name: "Adding Fractions",
      steps: ["Same denominator: add tops", "2 + 1 = 3", "Answer: 3/5"],
    },
  },

  // ========== GRADE 4: Place Value to Millions ==========
  {
    id: "place-mil-1",
    skillId: "place-value",
    difficulty: 3,
    question: "In 3,456, what digit is in the hundreds place?",
    answer: "4",
    choices: ["3", "4", "5", "6"],
    hint: "Count from the right: ones, tens, hundreds",
    explanation: "The hundreds place is the third digit from right: 4",
    vedicTrick: {
      name: "Place Value",
      steps: ["From right: 6 (ones), 5 (tens), 4 (hundreds), 3 (thousands)", "Answer: 4"],
    },
  },
  {
    id: "place-mil-2",
    skillId: "place-value",
    difficulty: 3,
    question: "What is 5,000 + 300 + 20 + 7?",
    answer: "5,327",
    choices: ["5,237", "5,327", "5,372", "5,732"],
    hint: "Add each place value",
    explanation: "5,000 + 300 + 20 + 7 = 5,327",
    vedicTrick: {
      name: "Expanded Form",
      steps: ["Line up by place value", "5,000 + 300 + 20 + 7", "Answer: 5,327"],
    },
  },
  {
    id: "place-mil-3",
    skillId: "place-value",
    difficulty: 4,
    question: "Round 4,763 to the nearest hundred",
    answer: "4,800",
    choices: ["4,700", "4,800", "4,760", "5,000"],
    hint: "Look at the tens digit (6)",
    explanation: "63 is closer to 100 than 0, so round up to 4,800",
    vedicTrick: {
      name: "Rounding",
      steps: ["Look at digit to the right of hundreds (6)", "6 ≥ 5, so round up", "Answer: 4,800"],
    },
  },
  {
    id: "place-mil-4",
    skillId: "place-value",
    difficulty: 4,
    question: "What is 10 times 4,250?",
    answer: "42,500",
    choices: ["4,260", "42,50", "42,500", "425,000"],
    hint: "Add one zero to the end",
    explanation: "Multiply by 10 adds one zero: 42,500",
    vedicTrick: {
      name: "Multiply by 10",
      steps: ["Multiplying by 10 shifts digits left", "Add a zero at the end", "4,250 → 42,500"],
    },
  },
  {
    id: "place-mil-5",
    skillId: "place-value",
    difficulty: 5,
    question: "In 2,345,678, what digit is in the ten thousands place?",
    answer: "4",
    choices: ["2", "3", "4", "5"],
    hint: "Count from right: ones, tens, hundreds, thousands, ten thousands",
    explanation: "Ten thousands is the 5th digit from right: 4",
    vedicTrick: {
      name: "Large Place Values",
      steps: ["From right: 8, 7, 6 (hundreds), 5 (thousands), 4 (ten thousands)", "Answer: 4"],
    },
  },

  // ========== GRADE 4: Measurement & Conversion ==========
  {
    id: "measure-conv-1",
    skillId: "measurement",
    difficulty: 3,
    question: "How many inches are in 1 foot?",
    answer: "12",
    choices: ["10", "12", "16", "24"],
    hint: "A ruler shows this",
    explanation: "1 foot = 12 inches",
    vedicTrick: {
      name: "Length Conversion",
      steps: ["Remember: 1 foot = 12 inches", "Like a ruler!", "Answer: 12"],
    },
  },
  {
    id: "measure-conv-2",
    skillId: "measurement",
    difficulty: 3,
    question: "How many feet are in 1 yard?",
    answer: "3",
    choices: ["2", "3", "4", "12"],
    hint: "Think about a yardstick",
    explanation: "1 yard = 3 feet",
    vedicTrick: {
      name: "Length Conversion",
      steps: ["1 yard = 3 feet", "Remember: yard has 3 letters after y!", "Answer: 3"],
    },
  },
  {
    id: "measure-conv-3",
    skillId: "measurement",
    difficulty: 4,
    question: "A rope is 2 feet long. How many inches is that?",
    answer: "24",
    choices: ["12", "20", "24", "36"],
    hint: "1 foot = 12 inches",
    explanation: "2 feet × 12 inches/foot = 24 inches",
    vedicTrick: {
      name: "Converting Measurements",
      steps: ["1 foot = 12 inches", "2 feet = 2 × 12 = 24 inches", "Answer: 24"],
    },
  },
  {
    id: "measure-conv-4",
    skillId: "measurement",
    difficulty: 4,
    question: "How many cups are in 1 pint?",
    answer: "2",
    choices: ["1", "2", "4", "8"],
    hint: "Think about milk cartons",
    explanation: "1 pint = 2 cups",
    vedicTrick: {
      name: "Capacity Conversion",
      steps: ["1 pint = 2 cups", "A pint of ice cream = 2 cups", "Answer: 2"],
    },
  },
  {
    id: "measure-conv-5",
    skillId: "measurement",
    difficulty: 4,
    question: "How many ounces are in 1 pound?",
    answer: "16",
    choices: ["8", "12", "16", "20"],
    hint: "More than a dozen",
    explanation: "1 pound = 16 ounces",
    vedicTrick: {
      name: "Weight Conversion",
      steps: ["1 pound (lb) = 16 ounces (oz)", "Remember: 16!", "Answer: 16"],
    },
  },
  {
    id: "measure-conv-6",
    skillId: "measurement",
    difficulty: 5,
    question: "A board is 6 feet long. How many yards is that?",
    answer: "2",
    choices: ["1", "2", "3", "18"],
    hint: "Divide by 3",
    explanation: "6 feet ÷ 3 feet/yard = 2 yards",
    vedicTrick: {
      name: "Converting Measurements",
      steps: ["1 yard = 3 feet", "6 ÷ 3 = 2", "Answer: 2 yards"],
    },
  },
  {
    id: "measure-conv-7",
    skillId: "measurement",
    difficulty: 5,
    question: "How many pints are in 1 gallon?",
    answer: "8",
    choices: ["2", "4", "8", "16"],
    hint: "2 cups = 1 pint, 4 quarts = 1 gallon",
    explanation: "1 gallon = 8 pints",
    vedicTrick: {
      name: "Capacity Conversion",
      steps: ["1 gallon = 4 quarts", "1 quart = 2 pints", "4 × 2 = 8 pints"],
    },
  },

  // ========== GRADE 4: Geometry & Angles ==========
  {
    id: "geo-angle-1",
    skillId: "geometry",
    difficulty: 3,
    question: "How many degrees are in a right angle?",
    answer: "90",
    choices: ["45", "90", "180", "360"],
    hint: "Like the corner of a square",
    explanation: "A right angle = 90 degrees",
    vedicTrick: {
      name: "Types of Angles",
      steps: ["Right angle = 90°", "Like a square corner", "Answer: 90"],
    },
  },
  {
    id: "geo-angle-2",
    skillId: "geometry",
    difficulty: 3,
    question: "What type of angle is less than 90°?",
    answer: "acute",
    choices: ["acute", "right", "obtuse", "straight"],
    hint: "Acute means 'sharp' or 'small'",
    explanation: "An acute angle is less than 90°",
    vedicTrick: {
      name: "Types of Angles",
      steps: ["Acute < 90°", "Right = 90°", "Obtuse > 90°"],
    },
  },
  {
    id: "geo-angle-3",
    skillId: "geometry",
    difficulty: 3,
    question: "How many degrees are in a straight line?",
    answer: "180",
    choices: ["90", "180", "270", "360"],
    hint: "Half a circle",
    explanation: "A straight angle = 180 degrees",
    vedicTrick: {
      name: "Types of Angles",
      steps: ["Straight angle = 180°", "Half of a full circle", "Answer: 180"],
    },
  },
  {
    id: "geo-angle-4",
    skillId: "geometry",
    difficulty: 4,
    question: "A triangle has angles 60°, 60°, and ?",
    answer: "60",
    choices: ["40", "50", "60", "70"],
    hint: "Triangle angles add to 180°",
    explanation: "60 + 60 + 60 = 180°",
    vedicTrick: {
      name: "Triangle Angle Sum",
      steps: ["All triangles have angles that add to 180°", "60 + 60 + ? = 180", "? = 60°"],
    },
  },
  {
    id: "geo-angle-5",
    skillId: "geometry",
    difficulty: 4,
    question: "What is the perimeter of a square with side 5 cm?",
    answer: "20 cm",
    choices: ["15 cm", "20 cm", "25 cm", "30 cm"],
    hint: "Add all 4 sides",
    explanation: "5 + 5 + 5 + 5 = 20 cm",
    vedicTrick: {
      name: "Perimeter of Square",
      steps: ["Square has 4 equal sides", "Perimeter = 4 × side", "4 × 5 = 20 cm"],
    },
  },
  {
    id: "geo-angle-6",
    skillId: "geometry",
    difficulty: 4,
    question: "A rectangle is 8 cm long and 3 cm wide. What is its perimeter?",
    answer: "22 cm",
    choices: ["11 cm", "22 cm", "24 cm", "32 cm"],
    hint: "Add: 8 + 3 + 8 + 3",
    explanation: "8 + 3 + 8 + 3 = 22 cm",
    vedicTrick: {
      name: "Perimeter of Rectangle",
      steps: ["Perimeter = 2 × (length + width)", "2 × (8 + 3) = 2 × 11 = 22 cm", "Answer: 22 cm"],
    },
  },
  {
    id: "geo-angle-7",
    skillId: "geometry",
    difficulty: 5,
    question: "What is the area of a rectangle 6 cm × 4 cm?",
    answer: "24 cm²",
    choices: ["10 cm²", "20 cm²", "24 cm²", "26 cm²"],
    hint: "Multiply length × width",
    explanation: "Area = 6 × 4 = 24 cm²",
    vedicTrick: {
      name: "Area of Rectangle",
      steps: ["Area = length × width", "6 × 4 = 24", "Answer: 24 cm²"],
    },
  },
  {
    id: "geo-angle-8",
    skillId: "geometry",
    difficulty: 5,
    question: "How many lines of symmetry does a square have?",
    answer: "4",
    choices: ["2", "4", "6", "8"],
    hint: "Vertical, horizontal, and 2 diagonals",
    explanation: "A square has 4 lines of symmetry",
    vedicTrick: {
      name: "Symmetry",
      steps: ["1 vertical line", "1 horizontal line", "2 diagonal lines", "Total: 4"],
    },
  },

  // ========== GRADE 5 ITEMS ==========
  // Place Value & Powers of 10
  { id: "g5-pv-1", skillId: "g5-place-value", difficulty: 1, question: "In 3,472,168, what is the value of the digit 4?", answer: 400000, choices: [4000, 40000, 400000, 4000000], explanation: "The 4 is in the hundred-thousands place: 400,000." },
  { id: "g5-pv-2", skillId: "g5-place-value", difficulty: 1, question: "45 × 1,000 =", answer: 45000, choices: [450, 4500, 45000, 450000], explanation: "Multiplying by 1,000 adds three zeros." },
  { id: "g5-pv-3", skillId: "g5-place-value", difficulty: 2, question: "6,300 ÷ 100 =", answer: 63, choices: [6, 63, 630, 6300], explanation: "Dividing by 100 removes two zeros." },
  { id: "g5-pv-4", skillId: "g5-place-value", difficulty: 2, question: "Round 48,671 to the nearest thousand.", answer: 49000, choices: [48000, 48700, 49000, 50000], explanation: "671 rounds up, so 48,671 → 49,000." },

  // Multi-Digit Multiplication
  { id: "g5-mult-1", skillId: "g5-mult", difficulty: 1, question: "324 × 6 =", answer: 1944, choices: [1844, 1944, 1924, 2044], explanation: "324 × 6 = 1,944." },
  { id: "g5-mult-2", skillId: "g5-mult", difficulty: 2, question: "45 × 23 =", answer: 1035, choices: [935, 1025, 1035, 1135], explanation: "45 × 23 = 1,035." },
  { id: "g5-mult-3", skillId: "g5-mult", difficulty: 2, question: "128 × 40 =", answer: 5120, choices: [512, 5120, 5220, 5012], explanation: "128 × 4 = 512, then add a zero: 5,120." },
  { id: "g5-mult-4", skillId: "g5-mult", difficulty: 3, question: "213 × 15 =", answer: 3195, choices: [3095, 3195, 3215, 3185], explanation: "213 × 15 = 3,195." },

  // Multi-Digit Division
  { id: "g5-div-1", skillId: "g5-division", difficulty: 1, question: "144 ÷ 12 =", answer: 12, choices: [11, 12, 13, 14], explanation: "12 × 12 = 144." },
  { id: "g5-div-2", skillId: "g5-division", difficulty: 2, question: "805 ÷ 5 =", answer: 161, choices: [151, 160, 161, 175], explanation: "805 ÷ 5 = 161." },
  { id: "g5-div-3", skillId: "g5-division", difficulty: 2, question: "672 ÷ 21 =", answer: 32, choices: [28, 31, 32, 34], explanation: "21 × 32 = 672." },
  { id: "g5-div-4", skillId: "g5-division", difficulty: 3, question: "936 ÷ 8 =", answer: 117, choices: [107, 117, 118, 127], explanation: "8 × 117 = 936." },

  // Decimal Operations
  { id: "g5-dec-1", skillId: "g5-decimals", difficulty: 1, question: "0.6 + 0.25 =", answer: 0.85, choices: [0.31, 0.65, 0.85, 0.9], explanation: "0.60 + 0.25 = 0.85." },
  { id: "g5-dec-2", skillId: "g5-decimals", difficulty: 2, question: "3.4 − 1.7 =", answer: 1.7, choices: [1.3, 1.7, 2.3, 2.7], explanation: "3.4 − 1.7 = 1.7." },
  { id: "g5-dec-3", skillId: "g5-decimals", difficulty: 2, question: "0.5 × 4 =", answer: 2, choices: [0.2, 0.9, 2, 20], explanation: "0.5 × 4 = 2." },
  { id: "g5-dec-4", skillId: "g5-decimals", difficulty: 2, question: "Round 7.38 to the nearest tenth.", answer: 7.4, choices: [7.3, 7.4, 7.0, 8.0], explanation: "The hundredths digit 8 rounds the tenths up: 7.4." },

  // Add & Subtract Fractions
  { id: "g5-asf-1", skillId: "g5-add-sub-fractions", difficulty: 1, question: "1/2 + 1/4 =", answer: "3/4", choices: ["2/6", "3/4", "1/4", "2/4"], explanation: "1/2 = 2/4, so 2/4 + 1/4 = 3/4." },
  { id: "g5-asf-2", skillId: "g5-add-sub-fractions", difficulty: 2, question: "2/3 + 1/6 =", answer: "5/6", choices: ["3/9", "5/6", "1/2", "3/6"], explanation: "2/3 = 4/6, so 4/6 + 1/6 = 5/6." },
  { id: "g5-asf-3", skillId: "g5-add-sub-fractions", difficulty: 2, question: "3/4 − 1/2 =", answer: "1/4", choices: ["1/4", "2/2", "1/2", "2/4"], explanation: "1/2 = 2/4, so 3/4 − 2/4 = 1/4." },
  { id: "g5-asf-4", skillId: "g5-add-sub-fractions", difficulty: 3, question: "5/6 − 1/3 =", answer: "1/2", choices: ["4/3", "1/2", "1/3", "4/6"], explanation: "1/3 = 2/6, so 5/6 − 2/6 = 3/6 = 1/2." },

  // Multiply & Divide Fractions
  { id: "g5-mf-1", skillId: "g5-mult-fractions", difficulty: 1, question: "1/2 × 1/3 =", answer: "1/6", choices: ["1/6", "2/5", "1/5", "2/6"], explanation: "Multiply across: (1×1)/(2×3) = 1/6." },
  { id: "g5-mf-2", skillId: "g5-mult-fractions", difficulty: 2, question: "2/3 × 3/4 =", answer: "1/2", choices: ["6/7", "1/2", "5/12", "6/12"], explanation: "6/12 simplifies to 1/2." },
  { id: "g5-mf-3", skillId: "g5-mult-fractions", difficulty: 2, question: "1/4 × 8 =", answer: 2, choices: [2, 4, 12, 32], explanation: "8 ÷ 4 = 2." },
  { id: "g5-mf-4", skillId: "g5-mult-fractions", difficulty: 3, question: "3 ÷ 1/2 =", answer: 6, choices: [1.5, 3, 6, 9], explanation: "Dividing by 1/2 is the same as multiplying by 2: 3 × 2 = 6." },

  // Expressions & Order of Operations
  { id: "g5-exp-1", skillId: "g5-expressions", difficulty: 1, question: "8 + 2 × 5 =", answer: 18, choices: [18, 50, 20, 26], explanation: "Multiply first: 2 × 5 = 10, then 8 + 10 = 18." },
  { id: "g5-exp-2", skillId: "g5-expressions", difficulty: 2, question: "(6 + 4) × 3 =", answer: 30, choices: [18, 24, 30, 42], explanation: "Parentheses first: 10 × 3 = 30." },
  { id: "g5-exp-3", skillId: "g5-expressions", difficulty: 2, question: "20 − 3 × 4 =", answer: 8, choices: [8, 68, 12, 17], explanation: "Multiply first: 3 × 4 = 12, then 20 − 12 = 8." },
  { id: "g5-exp-4", skillId: "g5-expressions", difficulty: 3, question: "24 ÷ (2 + 4) =", answer: 4, choices: [4, 8, 16, 12], explanation: "Parentheses first: 2 + 4 = 6, then 24 ÷ 6 = 4." },

  // Measurement, Volume & Data
  { id: "g5-meas-1", skillId: "g5-measurement", difficulty: 1, question: "How many centimeters are in 3 meters?", answer: 300, choices: [30, 300, 3000, 3], explanation: "1 m = 100 cm, so 3 m = 300 cm." },
  { id: "g5-meas-2", skillId: "g5-measurement", difficulty: 2, question: "A box is 4 cm by 3 cm by 2 cm. What is its volume in cubic cm?", answer: 24, choices: [9, 18, 24, 48], explanation: "Volume = length × width × height = 4 × 3 × 2 = 24." },
  { id: "g5-meas-3", skillId: "g5-measurement", difficulty: 1, question: "How many minutes are in 4 hours?", answer: 240, choices: [40, 120, 240, 400], explanation: "1 hour = 60 minutes, so 4 × 60 = 240." },
  { id: "g5-meas-4", skillId: "g5-measurement", difficulty: 2, question: "Convert 5 kilograms to grams.", answer: 5000, choices: [50, 500, 5000, 50000], explanation: "1 kg = 1,000 g, so 5 kg = 5,000 g." },

  // ========== GRADE 2 ITEMS (standards-aligned) ==========
  // Add within 100
  { id: "g2-add-1", skillId: "g2-add-100", difficulty: 1, question: "37 + 45 =", answer: 82, choices: [72, 82, 83, 92], explanation: "37 + 45 = 82." },
  { id: "g2-add-2", skillId: "g2-add-100", difficulty: 1, question: "58 + 26 =", answer: 84, choices: [74, 82, 84, 86], explanation: "58 + 26 = 84." },
  { id: "g2-add-3", skillId: "g2-add-100", difficulty: 2, question: "63 + 19 =", answer: 82, choices: [72, 81, 82, 92], explanation: "63 + 19 = 82." },
  { id: "g2-add-4", skillId: "g2-add-100", difficulty: 1, question: "40 + 55 =", answer: 95, choices: [85, 90, 95, 105], explanation: "40 + 55 = 95." },

  // Subtract within 100
  { id: "g2-sub-1", skillId: "g2-sub-100", difficulty: 1, question: "82 − 47 =", answer: 35, choices: [35, 45, 36, 25], explanation: "82 − 47 = 35." },
  { id: "g2-sub-2", skillId: "g2-sub-100", difficulty: 1, question: "70 − 26 =", answer: 44, choices: [44, 54, 46, 34], explanation: "70 − 26 = 44." },
  { id: "g2-sub-3", skillId: "g2-sub-100", difficulty: 2, question: "55 − 18 =", answer: 37, choices: [37, 43, 47, 33], explanation: "55 − 18 = 37." },
  { id: "g2-sub-4", skillId: "g2-sub-100", difficulty: 1, question: "91 − 40 =", answer: 51, choices: [41, 51, 61, 50], explanation: "91 − 40 = 51." },

  // Place Value to 1000
  { id: "g2-pv-1", skillId: "g2-place-value-1000", difficulty: 1, question: "What is the value of the digit 7 in 728?", answer: 700, choices: [7, 70, 700, 728], explanation: "The 7 is in the hundreds place: 700." },
  { id: "g2-pv-2", skillId: "g2-place-value-1000", difficulty: 1, question: "400 + 50 + 3 =", answer: 453, choices: [435, 453, 400, 543], explanation: "400 + 50 + 3 = 453." },
  { id: "g2-pv-3", skillId: "g2-place-value-1000", difficulty: 2, question: "What number is 10 more than 235?", answer: 245, choices: [236, 245, 335, 225], explanation: "235 + 10 = 245." },
  { id: "g2-pv-4", skillId: "g2-place-value-1000", difficulty: 2, question: "How many tens are in 260?", answer: 26, choices: [2, 6, 26, 260], explanation: "260 = 26 tens." },

  // Measurement & Length
  { id: "g2-meas-1", skillId: "g2-measurement", difficulty: 1, question: "How many centimeters are in 1 meter?", answer: 100, choices: [10, 100, 1000, 12], explanation: "1 meter = 100 centimeters." },
  { id: "g2-meas-2", skillId: "g2-measurement", difficulty: 2, question: "A pencil is 15 cm and a crayon is 8 cm. How much longer is the pencil?", answer: 7, choices: [7, 8, 23, 6], explanation: "15 − 8 = 7 cm." },
  { id: "g2-meas-3", skillId: "g2-measurement", difficulty: 1, question: "How many inches are in 1 foot?", answer: 12, choices: [10, 12, 100, 3], explanation: "1 foot = 12 inches." },
  { id: "g2-meas-4", skillId: "g2-measurement", difficulty: 2, question: "A 24 cm ribbon is cut into 2 equal pieces. How long is each piece?", answer: 12, choices: [8, 12, 22, 48], explanation: "24 ÷ 2 = 12 cm." },

  // Time to 5 Minutes
  { id: "g2-time-1", skillId: "g2-time", difficulty: 1, question: "How many minutes are in 1 hour?", answer: 60, choices: [30, 60, 100, 12], explanation: "1 hour = 60 minutes." },
  { id: "g2-time-2", skillId: "g2-time", difficulty: 1, question: "How many minutes are in a half hour?", answer: 30, choices: [15, 30, 45, 60], explanation: "Half of 60 is 30." },
  { id: "g2-time-3", skillId: "g2-time", difficulty: 2, question: "How many minutes is it from 2:00 to 2:45?", answer: 45, choices: [15, 30, 45, 60], explanation: "From :00 to :45 is 45 minutes." },
  { id: "g2-time-4", skillId: "g2-time", difficulty: 1, question: "How many minutes are in a quarter hour?", answer: 15, choices: [15, 20, 25, 30], explanation: "A quarter of 60 is 15." },

  // Money & Making Change
  { id: "g2-money-1", skillId: "g2-money", difficulty: 1, question: "How many cents are in a quarter?", answer: 25, choices: [5, 10, 25, 50], explanation: "A quarter = 25 cents." },
  { id: "g2-money-2", skillId: "g2-money", difficulty: 2, question: "2 dimes and 1 nickel = ? cents", answer: 25, choices: [15, 20, 25, 30], explanation: "10 + 10 + 5 = 25 cents." },
  { id: "g2-money-3", skillId: "g2-money", difficulty: 2, question: "How many cents are in 3 quarters?", answer: 75, choices: [50, 60, 75, 100], explanation: "3 × 25 = 75 cents." },
  { id: "g2-money-4", skillId: "g2-money", difficulty: 2, question: "You have 50 cents and spend 35 cents. How many cents are left?", answer: 15, choices: [15, 25, 20, 85], explanation: "50 − 35 = 15 cents." },
]

const TOPIC_TO_CATEGORY_MAP: Record<string, string[]> = {
  // Grade 1
  "addition-subtraction": ["operations-algebraic"],
  "number-sense": ["number-place-value"],
  measurement: ["measurement"],
  time: ["time"],
  money: ["money"],
  geometry: ["geometry"],
  "numerical-reasoning": ["operations-algebraic", "number-place-value"],
  "patterning-algebraic": ["operations-algebraic"],
  "measurement-data": ["measurement", "time", "money"],
  "geometric-spatial": ["geometry"],
  // Grade 2
  "add-sub-100": ["addition", "subtraction"],
  "place-value-1000": ["place-value"],
  "skip-counting": ["multiplication"],
  // Grade 3
  multiplication: ["multiplication"],
  division: ["division"],
  fractions: ["fractions"],
  "place-value": ["place-value"],
  // Grade 4
  "multi-digit": ["multiplication", "division"],
  "fractions-decimals": ["fractions"],
  "grade4-numerical-reasoning": ["multiplication", "division", "fractions", "place-value"],
  "grade4-patterning": ["operations-algebraic", "multiplication"],
  "grade4-measurement-data": ["measurement"],
  "grade4-geometric-spatial": ["geometry"],
  // Grade 5
  "g5-place-value": ["place-value"],
  "g5-operations": ["multiplication", "division"],
  "g5-decimals": ["decimals"],
  "g5-fractions": ["fractions"],
  "g5-expressions": ["operations-algebraic"],
  "g5-measurement": ["measurement", "geometry"],
}

export function getSkillsForTopics(grade: Grade, topicIds: string[]): Skill[] {
  if (topicIds.length === 0) {
    return getSkillsForGrade(grade)
  }

  const categories = topicIds.flatMap((topicId) => TOPIC_TO_CATEGORY_MAP[topicId] || [])
  return SKILLS.filter((s) => s.grade === grade && categories.includes(s.category))
}

export function getSkillsForGrade(grade: Grade): Skill[] {
  return SKILLS.filter((s) => s.grade === grade)
}

export function getItemsForSkill(skillId: string, difficulty?: number): MathItem[] {
  let items = MATH_ITEMS.filter((i) => i.skillId === skillId)
  if (difficulty !== undefined) {
    items = items.filter((i) => i.difficulty === difficulty)
  }
  return items
}

export function getRandomItem(skillId: string, difficulty: number): MathItem | undefined {
  const items = getItemsForSkill(skillId, difficulty)
  if (items.length === 0) {
    // Fallback to any difficulty if exact match not found
    const allItems = getItemsForSkill(skillId)
    return allItems[Math.floor(Math.random() * allItems.length)]
  }
  return items[Math.floor(Math.random() * items.length)]
}
